### ISSUE TITLE
Contributor instructions missing critical step

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xjava#100]
`xjava/README.md` should explain that after cloning xjava locally, the x-api server must be restarted to serve newly added problems.

I don't know if this would be true for pre-existing problems that have been modified.

**Comment by kytrinyx** [comment]
The xapi server doesn't use the xjava track directly. It includes xjava as a submodule. So if you have both the xapi and xjava, these don't conflict.

**Comment by kytrinyx** [comment]
That said... if you want to check how this would work out in x-api, then you would need to cd to `xapi/tracks/java` and do a git pull... and then restart the server.

**Comment by matthewmorgan** [comment]
I think I may have mis-explained the issue, or I don't understand what you mean.

I was describing the step where you run x-api locally to serve your local xjava and make sure the `exercism fetch java <myproblem>` correctly serves the exercise.

**Comment by kytrinyx** [comment]
Yeah, I think we probably explain that wrong in the docs, now that you bring it up.

**Comment by matthewmorgan** [comment]
So FMI does the server load everything into memory at start, or is it pointing at a previous commit of the xjava repository, so it doesn't see changes made after startup?

**Comment by kytrinyx** [comment]
It's pointing at a previous commit in the xjava repository. Each track is checked out separately and the repo that's living underneath x-api/tracks needs to be updated with the commit.

This is something that I've been doing manually whenever I need to and have completely and utterly forgotten to document.

**Comment by matthewmorgan** [comment]
@kytrinyx I still think I'm not explaining this correctly.  This is an issue I'm seeing locally when running x-api on my dev machine to test fetching a newly added exercise from my local copy of x-java.

I think the mistake I made was running `rackup` before changing `config.json` in the x-java root directory (local copy) to include the name of the new exercise.

It appears x-api is able to serve changes to the exercise directories without a restart.  EG, add or change a test, no problem-- the changes are downloaded on the next `exercism fetch`.  But it didn't see the change to config.json without restart, so it thought it didn't have that route.

I discussed this with @jtigger, and it got us to wondering what other files x-api reads only at startup.  In other words, what changes in the local xjava would require an x-api restart when developing?

Thanks!

**Comment by kytrinyx** [comment]
Aaaaah, yeah that is totally not the discussion I was having! Thank you so much for clarifying. I actually haven't looked at which files are cached after the first time they're read.

I think we should assume that any file could be cached and that the server should be restarted on any change to a local xjava file.

**Comment by matthewmorgan** [comment]
Yes, we can thank @jtigger for realizing that you and I were having two
different conversations  :)

I'm fine with telling them to restart after any change, @jtigger?

On Sun, Mar 13, 2016 at 1:10 PM, Katrina Owen <notifications@github.com>
wrote:

> Aaaaah, yeah that is totally not the discussion I was having! Thank you so
> much for clarifying. I actually haven't looked at which files are cached
> after the first time they're read.
>
> I think we should assume that any file could be cached and that the server
> should be restarted on any change to a local xjava file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xjava/issues/100#issuecomment-196002707>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Comment by kytrinyx** [comment]
Thank you @jtigger!

**Comment by matthewmorgan** [comment]
Closed by #113
