### ISSUE TITLE
Cannot deliver jar file via the JSON api

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#13]
The API currently blows up when trying to serve java problems, due to the non-utf-8 characters in the gradle archive.

It is perhaps a bit excessive to serve a jar file with each problem. Should we provide a link to the jar and have people download it and put it in their `PATH`?

Should we simplify the testing? (we really don't need anything fancy, the problems are all very tiny).

**Comment by jtigger** [comment]
Spoke with @kytrinyx about this, this morning.  Since this discussion, we've (rather by default) apparently settled on using a dependency management tool (i.e. Gradle).  Effectively, issue closed.
