### ISSUE TITLE
IntelliJ vs Eclipse - where to document what?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#132]
The https://github.com/exercism/xjava/blob/master/docs/INSTALLATION.md file talks about Eclipse, and the https://github.com/exercism/xjava/blob/master/docs/TESTS.md file talks about IntelliJ.

Am I missing something? Should both of these be documented in INSTALLATION (or perhaps both in TESTS)?

**Comment by jtigger** [comment]
Nope... what you're experiencing is the confusion that comes from two goals colliding in documentation:

1. Provide an opinionated and step-by-step (read: relatively context-free) set of instructions for new-to-the-language and Early Programmers.  The goal, here is to minimize the risk that someone new to the track gets ensnared in a setup issue.
  * both `INSTALLATION.md` and `TESTS.md` have instructions for installing/using IntelliJ, respectively.
2. Represent the major Java IDEs (including Eclipse [and soon, NetBeans](exercism/xjava#119)).  Make the instructions applicable to a wider audience by supporting programmers in their choice of tools.
  * in `INSTALLATION.md` there is an appendix for using Eclipse.  However, the second 3/4's of the file *should be moved* to `TESTS.md` in the event we want to provide instructions for multiple IDEs.
  * there's a pending PR that includes similar instructions for NetBeans.

I think we should stick to the former.  Two reasons:
1.  if you're experienced enough to have an opinion about which IDE to use, you're probably skilled enough to adapt these instructions to your tool of choice.
- each bit of documentation and code we maintain is maintenance — the smaller/simpler, the more track maintenance effort can go into improving the track.

This would mean:

1. revert the Eclipse instructions commits (dcec8e4702a22451e8f61ddb376c2266464d023d, c419b7206e509e1a65541c91e3f8c80f62afd1db)
- abort [the pending PR about add NetBeans instructions](exercism/xjava#119).
- adding a note at the top of the instructions making clear that these are *opinionated* instructions, acknowledging the presence of other IDEs with links to their install pages.

cc: @matthewmorgan , @sit , @pietvandongen

**Comment by kytrinyx** [comment]
Are there ways of running the tests without an IDE? Is this even a thing in Java?

If we do want to keep the instructions, we should

- keep them all in the same file
- have a table of contents at the top so people have an idea what to expect
- suggest one for those who do not yet have an opinion

**Comment by sit** [comment]
@kytrinyx An IDE is not necessary, you can install Java and then run `./gradlew test` if memory serves.

FWIW, I'm fine with recommending IntelliJ or recommending nothing.

**Comment by jtigger** [comment]
@sit said:
> @kytrinyx An IDE is not necessary, you can install Java and then run ./gradlew test if memory serves.

Yup.  In general, there's no reason we can't instruct users to install Gradle and use that.  We only have a gradle wrapper in the root module, not the exercises.  The wrapper includes a JAR and cannot be served by the CLI.

Options include:
- JDK only (with instructions on how to compile, obtain dependencies and manage the classpath and fire-up the JUnit runner from the command-line).
- JDK + Gradle (using an editor of their choice).
- JDK + an IDE.

For Early Programmers and New-to-the-language Programmers, I'd think that the last option would be the most welcoming.  It not only takes care of the details, but provides an environment rich in signals about what's not working.

**Comment by jtigger** [comment]
@kytrinyx said:

> If we do want to keep the instructions, we should
> * keep them all in the same file ...

So, in the language `./docs` directory, there is one page for "Installing (language)" and another for "Running The Tests".  I presume you mean keep like instructions in the right place (i.e. installation instructions for the IDEs in `INSTALLATION.md` and running the tests in each IDE in `TESTS.md`.  Did I get that right?

> * have a table of contents at the top so people have an idea what to expect
> * suggest one for those who do not yet have an opinion

Both of these make sense.

**Comment by kytrinyx** [comment]
> An IDE is not necessary, you can install Java and then run `./gradlew test`

That is fantastic. I think that JDK + IDE is nice and friendly, but it would drive me nuts to have to use an IDE when I could just run a command in the terminal. 

> The wrapper includes a JAR and cannot be served by the CLI.

We have implemented support for a "global" directory which can contain stuff we want to stick in the root of their exercism language track. It delivers a zipped archive, so we can handle the jar file.

We haven't implemented support for this in the CLI yet, though.

- https://github.com/exercism/x-api/blob/master/api/v3/routes/tracks.rb#L68
- https://github.com/exercism/x-api/issues/29
- https://github.com/exercism/x-api/pull/124

**Comment by kytrinyx** [comment]
> I presume you mean keep like instructions in the right place (i.e. installation instructions for the IDEs in INSTALLATION.md and running the tests in each IDE in TESTS.md.

Right, but the IDE stuff looks like "how to use the IDE" not "how to install the IDE", so to me that would go in the tests file.

**Comment by jtigger** [comment]
> That is fantastic. I think that JDK + IDE is nice and friendly, but it would drive me nuts to have to use an IDE when I could just run a command in the terminal.

I agree: I insist on knowing the terminal approach fairly early on when learning on a new platform.  Mostly because I know I'm doing CI, regardless and it's much easier to document CLI work.

We'll maintain CLI-only instructions too.

**Comment by jtigger** [comment]
> Right, but the IDE stuff looks like "how to use the IDE" not "how to install the IDE", so to me that would go in the tests file.

Yeah, the merge of the Eclipse instructions has really confused the `INSTALLATION.md` page.  The top portion of that page is nothing but *installation* instructions for JDK and IntelliJ (and the `TEST.md` page is nothing but running the tests in IntelliJ.

The Eclipse instructions are out of place.  Will fix.

**Comment by kytrinyx** [comment]
> The Eclipse instructions are out of place. Will fix.

Sweet!

**Comment by jtigger** [comment]
After writing up a full set of instructions for both the IDEs and command prompt setups, I've realized two things:

1. we do a really good job of introducing Early Programmers to the command prompt; we'd be doing them a disservice by shying away from it
-  Exercism problems, by design, are toys... on the order of 5-30 lines.  An IDE really only starts to be worth the learning curve once the project reaches a certain size.  In fact, the command prompt is the better tool for the job.

I'm going to seriously trim down the instructions.  We'll acknowledge the presence of IDEs, but the official instructions will be based on the command prompt.

**Comment by jtigger** [comment]
#136 resolves this.

**Comment by kytrinyx** [comment]
@jtigger 🎉 This is such a great improvement. Thank you!

**Comment by jtigger** [comment]
@matthewmorgan is of the same opinion.  Glad to know this landed in the right way. :)
