### ISSUE TITLE
Difficulty, Similarity and Order of Java Exercises

### ISSUE THREAD

**Issue by rcraggs** [exercism/xjava#134]
Hi posted this is the Github Education forum and was asked by @kytrinyx to re-post it as an issue here:

(original post - [https://education.github.community/t/fluency-vs-proficiency-when-teaching-learning-programming-and-ready-made-assignments-for-your-classroom/2479/3?u=rcraggs](https://education.github.community/t/fluency-vs-proficiency-when-teaching-learning-programming-and-ready-made-assignments-for-your-classroom/2479/3?u=rcraggs))

---

Hi Katrina

I love the idea of exercism.io. When I started to create a bootcamp for our students who had not yet picked up Java sufficiently well (our university's core teaching language) my idea was to use the exercises there as key way to learn. 

In trying to work out what order the students should attempt the exercises I tried to map which concepts were required to complete each exercise. This was my attempt - https://docs.google.com/spreadsheets/d/1-jHZex1oMRk2eJxCkHfWK1MXaIFkVWQt2hUhDUih198/pubhtml?gid=0&single=true

What I found was
1. There are relatively few exercises that are accessible for an absolute beginner. A fairly high proportion of them require string manipulation or use of Maps, which in the teaching material we use, aren't introduced until later. 
2. A lot of the exercises are similar, e.g. processing a string to calculate some properties of the text within it. 

What I did to combat this was to create exercises that a student can complete to introduce the more basic concepts (loops, conditions) and build up to their first exercism exercise. I also curated and ordered the exercism exercises so that they could avoid doing multiple similar exercises. The results is this - https://github.com/rcraggs/learn-some-java/

A similar idea is Koans https://github.com/ahmdrefat/awesome-koans although this lacks the social aspect that exercism.io does so well.

**Comment by kytrinyx** [comment]
Thank you @rcraggs.

@exercism/java There are a few things I wonder if we can do to improve the track.

1. That spreadsheet! Can we use this as a basis for assigning topics?  #125
2. Can we make up some new exercises inspired by the ones that @rcraggs created in order to provide a more gentle on-ramp?
3. Should we do some measurements with respect to the exercises with duplication? Are there sharp drop-offs? Do people suffer from exercise fatigue? Should we try to temporarily deprecate some of the exercises that are too similar to others? (Or try to make them more different?)

**Comment by matthewmorgan** [comment]
@rcraggs I do think it makes sense to revisit the ordering of exercises here. 

@kytrinyx 
1. Spreadsheet is a good idea.  
2.  @rcraggs' exercises do provide a lower barrier to entry.  If it seems like a good idea to add these,  is this something that belongs in x-common generally, rather than just in Java?
3. I think the stats graphs could help us understand the answers to these questions.  It might also be interesting to compare a track that adheres fairly closely to the spreadsheet referenced in (1), like EcmaScript (I think!) to the Java track.

**Comment by kytrinyx** [comment]
> Spreadsheet is a good idea.

Sorry, I was unclear. @rcraggs already did a bunch of work in the spreadsheet he linked to.

**Comment by kytrinyx** [comment]
> If it seems like a good idea to add these, is this something that belongs in x-common generally, rather than just in Java?

Yepp, that would be general exercises that any of the tracks could implement if they wanted to.

**Comment by jtigger** [comment]
@matthewmorgan and I are going to take a first cut at reordering in #142.

**Comment by jtigger** [comment]
@matthewmorgan and I took some time this morning to review the stats pages on exercism.  We're going to use those metrics to see what affect re-ordering is having on engagement.

**Comment by hajush** [comment]
I'm a bit confused here if I don't understand context, but I thought the first few exercism.io exercises in JavaScript were in a reasonable order. But in Java, going straight from hello-word into Etl was too huge of a leap.... Where is leap? hamming? 14 missing exercises before Etl in JavaScript. I'm writing the leap one now, just so I can spare my students the deep dive. Is there something I'm missing? Why so many missing exercises? Is it just missing labor, or is there another reason? Thanks!

**Comment by jtigger** [comment]
We could absolutely use the help in implementing exercises.  @hajush , you've caught us right in the middle of an effort of evaluating the track of exercises.  We expect to add more, get rid of a few and reorder many.

We're painfully aware of the bumpy road along this track and very happy to collaborate with those who can help.

Helping us implement exercises is a HUGE help.

**Comment by kytrinyx** [comment]
If it helps, there's a bit of documentation about how to port exercises: https://github.com/exercism/exercism.io/blob/master/docs/porting-an-exercise.md

**Comment by stkent** [comment]
Now that basic ordering is implemented, is it time to close this issue? cc @jtigger @matthewmorgan

**Comment by jtigger** [comment]
There are two aspects to this issue.  The first is the difficulty rating.  The second are the topics.  We've taken the first (big) step to address difficulty.  But the second remains.  That said, I'm not sure that the Java track is the right place to flesh-out what "topics" are and how they are used.

For the topics aspect, I'm going to go look to see if there are other conversation happening around the topic of ... topics. :)  I know there was some when the idea first emerged...  At the very least, I'll reposition references to @rcraggs's work there as well.

For xJava, I'm going to open up a question-issue to serve as a backbone for general track "health".  From there, I think we'll spawn additional efforts around establishing ways for us to navigate...

With those in place, we can consider this issue "done."

**Comment by stkent** [comment]
Sounds good! I wasn't looking forward to the effort involved in adding topics to the track given there's no current value-add.
