### ISSUE TITLE
Come up with a draft ordering of the exercises in xJava

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#142]

**Comment by jtigger** [comment]
I'm gonna share my ongoing thoughts, here, as I continue through the track.

* (as I've said in another ticket) `Gigasecond` seems trivial in the Java track.
- `binary` and `roman-numeral` are very similar kinds of problems.  In fact, I feel like `roman-numeral` is a fun revisit of `binary` with some twists.
-

**Comment by matthewmorgan** [comment]
@jtigger did you see the comment I made on this?  It seems to be gone...?

**Comment by jtigger** [comment]
@matthewmorgan I saw it.  That was on a separate issue: #143

**Comment by matthewmorgan** [comment]
I'm losing it!  thanks :)

**Comment by jtigger** [comment]
...wait... you had it? ;)

**Comment by jtigger** [comment]
@exercism/java: the track is about to pick-up this work in earnest.

I've found that taking the time to understand *why* we're doing a work yields higher quality outcomes.

Please take a moment to consider and share your thoughts: **why does the Java track of Exercism exist?  What purpose does it serve?  Whom does it serve?**

**Comment by jtigger** [comment]
@exercism/java I've created a spreadsheet for us to collect our assessments https://docs.google.com/spreadsheets/d/15UbVn4cBUxI7tekKmNNls9dXsT1rDhtG7Z8lp1nmjlM/edit

Please fill-out the sheet according to your assessment:

- share your thoughts in the `Notes` tab;
- name the topics invoked by the exercise in the `Topics` tab;
- estimate the difficulty of the exercise in `Difficulty` tab.

You might find #134 inspiring.

Thanks!

**Comment by stkent** [comment]
Will take a crack at this over the holidays :)

**Comment by jtigger** [comment]
FWIW, I've started to settle on an "intrinsic complexity" measure.  I see two primary sources of complexity:

1. that arising from required interfaces (i.e. methods and data structures)
2. that arising from required behavior (i.e. operations)

I'm capturing this in another tab in the spreadsheet.  If you're interested, take a look. I figure behavior complexity has more of an impact than interface complexity on how hard the problem is, so I put a coefficient in front of them.  I'll sort by that complexity rating and see what I get!

Very interested in how others are tackling this problem (of identifying order of exercises).

**Comment by jtigger** [comment]
Please signal here when you've add your input.

**Comment by stkent** [comment]
I've added difficulty rankings based on manual inspection of the problem descriptions and test suites. They align fairly well with @jtigger's rankings! I probably won't have time to get to the topics list any time soon - busy times ahead.

**Comment by jtigger** [comment]
Yeah, thankfully we're not worlds apart! :)  I've tossed some stats over the current rankings.  For those who haven't voted, you might want to prioritize your votes for the exercises that have a standard deviation of 1 or greater (marked in red).

**Comment by stkent** [comment]
Great idea!

**Comment by jtigger** [comment]
Yeah, and "topics" seem like a whole 'nother thing... I'm aware of the general idea of how it can be valuable, but I am not clear one or more use-cases that motivate the use of that data.  Also, if a particular exercise aims for a specific topic, shouldn't it be attributed to that exercise (i.e. in `x-common`)?  So, what's the additional topics that are language-specific?

many questions. :)

For that reason, I'm personally interested in *just* the difficulty, first.

**Comment by stkent** [comment]
For sure; it's also not clear to me how we handle topics that may or may not touched on by an exercise depending on implementation choices...

Also, I only just realized that we will need to manually decide on an exercise order - the order is not absolutely controlled by difficulty. The difficulty ranking should be a great starting point for that sort, however!

**Comment by jtigger** [comment]
@FridaTveit, I've created a column for you on the spreadsheet should you want to jump in on this.

**Comment by FridaTveit** [comment]
Thanks! :)

**Comment by jtigger** [comment]
At this time, the task at hand is to close the gap on the exercises which have a standard deviation > 1 (in appears with red background in spreadsheet).

I can think of some resolution paths:

1. John and Stuart can share their rationale for their scoring, possibly convincing one or the other to change their rating.
2. Emit, Frida, or Matt could add their vote on these exercises.  Presumably, this would close the gap.
3. Ignore the difference and go with the average.  To @stkent's point, difficulty does not *have* to be the only variable in ranking.
4. ...

**Comment by jtigger** [comment]
added `matrix`, `twelve-days`, and `rectangles` to the spreadsheet.

**Comment by stkent** [comment]
I think getting _some_ sensible order in place is a reasonably high priority; currently, track newcomers are hit with ETL as the second exercise which is probably not a very friendly welcome. I'd support using the existing scores to seed the preliminary ordering, with the understanding that issues/PRs proposing sequencing changes (with reasoning) are both welcomed and encouraged. That iterative philosophy also fits better with the mutation of exercises that will occur as the canonical test suites change.

This assumes that `exercism fetch` is robust as exercise order changes, i.e. that it fetches "the earliest exercise not yet completed" rather than "the exercise following your most recently-completed exercise in the track sequence"...?

**Comment by jtigger** [comment]
Well put, @stkent; I wholeheartedly agree.

I'm fairly certain that the CLI works that way.  I'll double-check.

**Comment by stkent** [comment]
Awesome; once you confirm, I'll open up a PR based on the shared spreadsheet!

**Comment by jtigger** [comment]
Okay... I've confirmed.  The next fetched exercise is determined by taking the entire track, subtracting all problems for which the user has submitted and grabbing the top of that list:

https://github.com/exercism/x-api/blob/7919a00f0d266652ad14d22044892b5e13acd51f/api/v1/routes/exercises.rb#L45

This makes re-ordering the track a very safe operation.

----

Current difficulty profile:
![current](https://cloud.githubusercontent.com/assets/470176/22770472/a8cb149c-ee45-11e6-906d-d7ca64367dc7.png)

Sorted by average score:
![new](https://cloud.githubusercontent.com/assets/470176/22770489/c7698348-ee45-11e6-9cd2-9e59d0c8a5e1.png)

_Major change_, here!  Super excited!

**Comment by stkent** [comment]
That second graph is so purdy! Thanks for checking out the CLI behavior, John - glad that behaves as expected. I'll reply to your question on the difficulty ranking spreadsheet now, and once that's resolved, open up the reordering PR.

**Comment by jtigger** [comment]
We've applied this first round of ordering... there's a _flight_ of stories around improving the overall experience... weeeeeeeee!

Considering this first move as done.
