### ISSUE TITLE
Remove Gigasecond; it's worthless in Java.

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#143]
All the interesting date math that this exercise probably brings in other languages is roundly covered with the built-in `java.time` package.

Worse, every solution I've seen submitted is nearly identical and so there's no room for discussion.

Unless we see this as a way to introduce that part of the standard library (which generally isn't the goal), this exercise doesn't yield the good stuff we're looking for.

**Comment by matthewmorgan** [comment]
That makes sense to me.  Plenty of more valuable exercises...!

**Comment by jtigger** [comment]
@exercism/java are we missing anything, here?

**Comment by stkent** [comment]
It might still be useful to leave this in for comparison with the date/time handling of other languages. Once exercises are assigned difficulties, this could be a starter exercise that pleasantly surprises newcomers to Java.

**Comment by kotp** [comment]
In Ruby there isn't even date/time considerations, aside from what the test chose to use for it.

**Comment by jtigger** [comment]
>It might still be useful to leave this in for comparison with the date/time handling of other languages. Once exercises are assigned difficulties, this could be a starter exercise that pleasantly surprises newcomers to Java.

Well, shoot; that's fair.

**Comment by jtigger** [comment]
Per this discussion, we're keeping it.

**Comment by stkent** [comment]
FWIW, I watched someone complete this exercise today, and it was the first time they discovered and used multiple constructors, and the first time they learned you could call into one constructor from another!
