### ISSUE TITLE
Ensure parameterized tests display the input value (instead of the index)

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#147]
There are a number of tests in this track that leverage the `Parameterized` test runner.  This is great except that the value being passed into the test is not displayed.  When a test fails, it's unnecessarily difficult to determine which case failed.

See https://github.com/junit-team/junit4/wiki/parameterized-tests#identify-individual-test-cases.

_(see related issues, below for each instance)_

**Comment by stkent** [comment]
@jtigger all issues that link back to this one are now closed; is this issue safe to close also?

**Comment by jtigger** [comment]
Whoops! Missed your mention, here, @stkent ... yeah, closing.  🎉
