### ISSUE TITLE
We sometimes have symlinks—is this intentional?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#148]
I'm working on repackaging the core logic of x-api into a ruby gem to support one of the longer-term refactorings I'm working on.

When I build the gem I get the following warnings:

```
WARNING:  tracks/java/exercises/allergies/src/example/java/Allergen.java is a symlink, which is not supported on all platforms
WARNING:  tracks/java/exercises/meetup/src/example/java/MeetupSchedule.java is a symlink, which is not supported on all platforms
WARNING:  tracks/java/exercises/triangle/src/example/java/TriangleException.java is a symlink, which is not supported on all platforms
WARNING:  tracks/java/exercises/triangle/src/example/java/TriangleKind.java is a symlink, which is not supported on all platforms
WARNING:  tracks/kotlin/exercises/allergies/src/example/kotlin/Allergen.kt is a symlink, which is not supported on all platforms
```

So we have symlinks in some places but not all.

What do the symlinks support?

**Comment by jtigger** [comment]
So, in the Java track, there are three source sets:

- the test code
- the example code (solving the tests)
- the served starter code

Sometimes, there are supporting files in the "starter" code that is (obviously) needed in the example code.  The symlink ensures that those supporting classes are identical between what's served to the user and what's used in the example.

I have no idea if this works on Windows.  I know it works on *nix.

It's not like this code changes all that much; it was just one less thing to get right when the exercise *does* change.

Would you like us to back this out?

**Comment by kytrinyx** [comment]
@jtigger If this is potentially a windows problem, this is not a problem at all, because we'll only ever be using *nix servers for Exercism.

So this isn't a problem at all.

Thanks for clarifying!
