### ISSUE TITLE
Add issue to Discussion for implementing labelling system where anyone can apply a label to a solution.  Should anyone be everyone?

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xjava#150]
@jtigger and I discussed the idea of users being able to add "labels" to exercise submissions.  EG, 'functional', 'class-based', etc.  The idea is to allow users to easily find (and perhaps follow) solution in a certain style or with some other distinctive characteristics.
1.  Should anyone , or just mentors/maintainers be able to label exercise submissions?
2.  How do labels get created?  Pull requests?

Follow up:
1. Create issues to implement this feature
2. Make a plan to roll out the feature (label a certain set of solutions?)

**Comment by stkent** [comment]
@matthewmorgan just doing some issue triage; it would appear that this issue is resolved per the stated scope ("Add issue to Discussion for implementing labelling system where anyone can apply a label to a solution" - this issue has been added and discussed). Can this xjava issue be closed? Cheers!

**Comment by matthewmorgan** [comment]
@stkent I think the intention was that the label would be added on the exercism.io UI, so I don't _think_ this feature is available, but correct me if I'm wrong.

It also occurs to me that xjava is probably not the best place for this issue.  Maybe it should be moved to discussions, or exercism.io.  What do you think?

**Comment by jtigger** [comment]
This was a reminder to Matt and I (at one point we were the crew keeping the lights on) to post that notion in exercism/discussion.

It *is* there.  We can close *this* issue.

**Comment by stkent** [comment]
@jtigger ah, yes, that's what I suspected, but didn't state especially clearly. Thanks!

**Comment by matthewmorgan** [comment]
Thanks for clearing this up!
