### ISSUE TITLE
Journey Test should continue to work as we move to "exercises" structure

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#154]
#125 calls for adjusting `bin/journey-test.sh` to iterate over `exercises` instead of `problems` before that key goes away.

**Comment by jtigger** [comment]
@exercism/java — anyone interested in deep-diving in our CI setup?  The script might seem overwhelming, at first, but with a short tour, I believe it is quite accessible.

Anyone want to help me test that hypothesis? :)

**Comment by FridaTveit** [comment]
I'll have a go :)

**Comment by stkent** [comment]
@jtigger @FridaTveit I think this issue can be closed now, right?

**Comment by FridaTveit** [comment]
I think so :)

**Comment by jtigger** [comment]
Yes!

**Comment by stkent** [comment]
Awesome!
