### ISSUE TITLE
Upgrade Gradle Wrapper to latest version of Gradle

### ISSUE THREAD

**Issue by sit** [exercism/xjava#158]
Apparently Java 8 and old versions of Gradle don't get along well (as per #156). We should be using a more recent version of Gradle in all projects.

**Comment by jtigger** [comment]
Agreed.

There are two ways in which we're including Gradle:

- as part of the repo, itself, at the root: i.e.`./exercises`; but not using the wrapper;
- for users through the installation instructions.

The challenge from #156 had to do with the latter.  The instructions bias users to employ the package manager on their platform; not sure why anyone of those are serving Gradle 1.x.  At the "worst" I expect the latest 2.x.

What could we do about that?

**Comment by sit** [comment]
Ah. The problem is that Ubuntu Trusty (several years old) comes with 1.4 as default. Even the latest Ubuntu seems to only use 2.10 or so.

Really I would prefer to use Gradle Wrapper because that would allow us to control the user experience more precisely. I know at one point we couldn't do that because binary files couldn't be sent by exercism client. Is that still true?

If we can't use the wrapper, then it may be that a PPA is the best solution for Linux users (in which case #156 is exactly the right PR).

**Comment by jtigger** [comment]
That is still true: CLI does not distribute binaries.

Now reading through #156 details, I now remember having gone down that path (I spent a lot of time trying to iron out install instructions for *nix).  IIRC, that PPA is Trusty specific.  If the user is on a later release, the existing instructions work on a broader set of distros.

Let's avoid wack-a-mole: if a PR like #156 fixes a specific release, let's make sure it doesn't break other releases (if so, make clear which instructions work for which release).

Am I making sense?

**Comment by jtigger** [comment]
Okay... I tried the cwchien PPA for gradle and it worked fine for both distros previously tested against (Linux Mint 18 and Ubuntu 14)... reviving the PR.
