### ISSUE TITLE
roman-numerals: make test failures easier to troubleshoot

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#160]
[`roman-numerals`](https://github.com/exercism/xjava/blob/master/exercises/roman-numerals/src/test/java/RomanNumeralsTest.java) uses the JUnit [`Parameterized`](https://github.com/junit-team/junit4/wiki/parameterized-tests) test runner.  This was done to make the test more compact (and once you learn how the mechanism works, easier to read).

However, when a test fails, the error message does not indicate which value failed.  This makes it really difficult to know why the test failed.

Test failures should clearly indicate what failed.

**To Do:**
- [x] ensure that this exercise is using JUnit 4.12 or later
- [ ] add a format string to the `@Parameters` annotation.

_(ref: #147)_

**Comment by stkent** [comment]
Related: https://github.com/exercism/x-common/pull/451

**Comment by bscharm** [comment]
@jtigger is a more "documentation style" description preferred? or a more sentence style description? e.g.:

`@Parameters(name = "#getRomanNumeral() for RomanNumeral({0}) should return \"{1}\"")`
translates to:
`[#getRomanNumeral() for RomanNumeral(3) should return "III"]`

vs.

`@Parameters(name = "Roman Numeral representation of {0} is \"{1}\"")`
translates to:
`[Roman Numeral representation of 3 is "III"]`

**Comment by jtigger** [comment]
@bscharm implementer's choice.  Which would you find more useful as the practitioner running through the exercise?
