### ISSUE TITLE
Refactoring of word-count test

### ISSUE THREAD

**Issue by alebaffa** [exercism/xjava#167]
Hi, 
in the [word-count exercise](https://github.com/exercism/xjava/blob/master/exercises/word-count/src/test/java/WordCountTest.java) I see that all the tests always start with the same two initializations:

```
Map<String, Integer> actualWordCount = new HashMap<String, Integer>();
final Map<String, Integer> expectedWordCount = new HashMap<String, Integer>();
```

This makes the tests quite verbose.
In order to make them easier to read, they could be could be transformed as global objects and their instantiation moved in a @Before method that can run before every @Test. Like so:

```
private WordCount wordCount;
private Map<String, Integer> actualWordCount;
private Map<String, Integer> expectedWordCount;

@Before
public void setUp(){
        wordCount= new WordCount();
        expectedWordCount = new HashMap<>();
}
```
(note: the instantiation of expectedWordCount is local to every test. 
I'm also moving the instantiation of WordCount() in the setUp method for coherence).

I think that this way the tests are easier to read since they now contain only the relevant information necessary to prepare the expected result, the call to the _production method_ and the assert.

What do you think?

**Comment by jtigger** [comment]
Solid.  To initialize `WordCount` only once for the whole suite is to know too much about how the class operates (specifically whether it's stateful for some reason).

**Comment by alebaffa** [comment]
WordCount is already initialized only once for the whole suite. For the moment it's a global private variable used by all the test cases (showed below). Moving it into a SetUp would make no difference.
```
public class WordCountTest {

    private final WordCount wordCount = new WordCount();
```

**Comment by jtigger** [comment]
You're saying that making a chance would make no difference to how the test/exercise operates.  That is true..... so long as the author does not create and maintain state for some reason.

Now, I understand that making such a suggestion sounds silly.

The rationale is to make as few assumptions/constraints on the solution as reasonable.  Should the author decide to create state, there's no reason why we should prevent that.

Adopting the habit of initializing all participants in a test helps avoid test pollution.  There are no tests to test the tests. :)  So, let's encourage a conservative approach to writing tests.
