### ISSUE TITLE
Anagram exercise doesn't include gradle build file

### ISSUE THREAD

**Issue by pietvandongen** [exercism/xjava#17]
When doing an ``exercism fetch`` and getting the *anagram* exercise, it doesn't contain a build script (``build.gradle`` file), making me unable to complete the exercise.

After I do ``exercism fetch``, I get (on OS X 10.10.2, using exercism-cli):

```

                     New: 1 problem
           Anagram (java) /Users/pietvandongen/exercism/java/anagram

unchanged: 25, updated: 0, new: 1
```

The directory listing (``ls -la anagram/``) gives:

```
total 8
drwxr-xr-x  4 pietvandongen  staff  136  1 feb 21:59 .
drwxr-xr-x  8 pietvandongen  staff  272  1 feb 21:59 ..
-rw-r--r--  1 pietvandongen  staff  360  1 feb 21:59 README.md
drwxr-xr-x  3 pietvandongen  staff  102  1 feb 21:59 src
```

**Comment by pietvandongen** [comment]
A working solution is to copy the ``build.gradle`` from another exercise (in this case, I copied it from the *bob* exercise, but they seem to be the same for all) to the *anagram* exercise (e.g. ``cp bob/build.gradle anagram/``).

**Comment by kytrinyx** [comment]
Ah thanks!

**Comment by kytrinyx** [comment]
Ok, that should be fixed. Thanks for the heads up!

**Comment by pietvandongen** [comment]
@kytrinyx Wow, that was quick, thank you!
