### ISSUE TITLE
It would be helpful to get an empty class (or at least directory structure) for new exercises

### ISSUE THREAD

**Issue by pietvandongen** [exercism/xjava#18]
For example, after I do a ``exercism fetch`` and I get a new problem, its directory exists of the following tree:

```
exercise-name/
├── README.md
├── build.gradle
└── src
    └── test
        └── java
            └── AnagramTest.java
```

When I want to work on the exercise, I always have to add a ``src/main/java`` directory by hand, and a class, resulting in the following tree (for example for the *bob* exercise):

```
bob/
├── README.md
├── build.gradle
└── src
    ├── main
    │   └── java
    │       └── Bob.java
    └── test
        └── java
            └── BobTest.java
```

**Comment by kytrinyx** [comment]
Yeah, we should probably provide at least the directory structure, and perhaps an empty file (or a skeleton file.

**Comment by kytrinyx** [comment]
Ok, done. Deploying now.

Thanks for the suggestion!

**Comment by pietvandongen** [comment]
@kytrinyx Awesome, thank you very much!

P.S.: You can close a GitHub issue with your commit, see https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by kytrinyx** [comment]
I know, I just forget about half the time.
