### ISSUE TITLE
Investigate track health and status of the track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#180]
I've used Sarah Sharp's [FOSS Heartbeat](https://github.com/sarahsharp/foss-heartbeat) project to generate stats for each of the language track repositories, as well as the x-common repository.

The Exercism heartbeat data is published here: https://exercism.github.io/heartbeat/

When looking at the data, please disregard any activity from me (`kytrinyx`), as I would like to get the language tracks to a point where they are entirely maintained by the community.

Please take a look at the heartbeat data for this track, and answer the following questions:

* To what degree is the track maintained?
* Who (if anyone) is merging pull requests?
* Who (if anyone) is reviewing pull requests?
* Is there someone who is not merging pull requests, but who comments on issues and pull requests, has thoughtful feedback, and is generally helpful? If so, maybe we can invite them to be a maintainer on the track.

I've made up the following scale:

* **ORPHANED** - Nobody (other than me) has merged anything in the past year.
* **ENDANGERED** - Somewhere between ORPHANED and AT RISK.
* **AT RISK** - Two people (other than me) are actively discussing issues and reviewing and merging pull requests.
* **MAINTAINED** - Three or more people (other than me) are actively discussing issues and reviewing and merging pull requests.

It would also be useful to know if there a lot of activity on the track, or just the occasional issue or comment.

Please report the current status of the track, including your best guess on the above scale, back to the top-level issue in the discussions repository: https://github.com/exercism/discussions/issues/97

**Comment by jtigger** [comment]
**MAINTAINED**

Since June 2016:

- maintainers are: @matthewmorgan, @jtigger, @sit;
- maintainers respond to PRs and issues within a day;
- the average open time of PRs is down from 63 days to 5 days;
- maintainers are actively and expeditiously participating in cross-track efforts;
- notably, @stkent has made numerous contributions in the form of high quality PRs.

**Comment by stkent** [comment]
Can confirm that maintainers have responded in a very timely manner and with very thorough responses to the aforementioned PRs 👍

**Comment by kytrinyx** [comment]
@stkent I love hearing this. Kudos to the maintainers for being awesome and responsive :heart:

> the average open time of PRs is down from 63 days to 5 days

Badass.

I've been doing some querying in BigTable against the GitHub Archive dataset, and extracted the "time to first response" on track issues.

I haven't actually figured out how to graph it yet, but here's the raw data for the past few weeks (issues only, I still need to get the data for pull requests).

The fields are:

* repo
* isoweek (year, week number)
* count of issues in that week
* average time to first comment in minutes (for reference: 1440 minutes in a day)

```
exercism/xjava,201603,1,442.0
exercism/xjava,201604,1,1458.0
exercism/xjava,201605,1,44.0
exercism/xjava,201609,2,3196.0
exercism/xjava,201613,2,3578.5
exercism/xjava,201614,3,357.66666666666663
exercism/xjava,201621,1,171284.0
exercism/xjava,201633,1,18461.0
exercism/xjava,201635,1,23470.0
exercism/xjava,201636,2,1187.0
exercism/xjava,201637,1,9763.0
exercism/xjava,201638,3,3525.0
exercism/xjava,201640,2,28511.5
exercism/xjava,201643,1,2590.0
exercism/xjava,201644,2,2506.5
exercism/xjava,201646,2,1077.5
exercism/xjava,201653,1,8136.0
```

**Comment by jtigger** [comment]
Yeah, that's not at all same-day responsiveness. :-}

But that's an excellent metric to track for awareness!

A little strange that ISO week 201653 is reported on despite it not happening yet...

**Comment by jtigger** [comment]
![image](https://cloud.githubusercontent.com/assets/470176/20511908/d99f3542-b030-11e6-9f8e-6e90ad2a7f3d.png)

https://docs.google.com/spreadsheets/d/137_U8uu2PZwETlo8uAsO7CkhuLTudW6bQfhGPK13gCU/edit#gid=0

**Comment by kytrinyx** [comment]
How did you... magical!

Yeah the 2016-53 is an odd duck. I wonder where that came from.

**Comment by kytrinyx** [comment]
Thanks, all, for weighing in!
