### ISSUE TITLE
Compilation Issues Related To Enums

### ISSUE THREAD

**Issue by robbiemacg** [exercism/xjava#216]
Exercises where enums are provided will not compile within the project directory (~/exercism/java/[exercise]/src/main/java/) on some systems. Neither user generated solutions nor the examples from the repo will compile, because the enums are not getting found... despite being in the same directory. 

So, the 'meetup' exercise, the 'triangle' exercise, etc. encounter compilation errors… unless classes are compiled in some other directory, then copied back to the project directory for testing. There's no problem with compilation if it happens in the home directory, in another exercism exercise's directory ('hamming' or something). I'm at a loss.

I've completed these exercise, am moving on, but this was incredibly frustrating, and still makes no sense to me. I'd love it if someone was able to share some insight. My environment is:

Fedora 22
javac 1.8.0_91
openjdk 1.8.0_91

**Comment by stkent** [comment]
@robbiemacg interesting, thanks for the report! A few follow-up questions:

- What is the shortest set of commands that cause the issue? (e.g. if you `fetch` the exercise, then immediately run `gradle test`, does _that_ fail compilation?) 
- Alternatively, what `javac` command are you running (and from where) to reproduce the issue?
- Have you tried`robot-simulator` yet? That includes both a provided enum and a provided class, and I'd be curious to know what you observe in that case.

**Comment by jtigger** [comment]
That's a major pain!

So, I couldn't find a virtualbox image for Fedora 22, but I found one for Fedora 23.

I followed the install instructions for the [cli](http://exercism.io/cli/linux) and [java and gradle](http://exercism.io/languages/java/installing#fedora) (the later being the far more important bit, here).

So, I'm testing with:
Fedora 23
javac 1.8.0_111
openjdk 1.8.0_111

Not exactly the same, but close.

```
$ exercism fetch java meetup
$ cd ~/exercism/java/meetup
$ cat << EOF > src/java/main/Meetup.java
import java.time.DayOfWeek;

public class Meetup {
  public Meetup(int a, int b) { }
  public Object day(DayOfWeek dow, MeetupSchedule schedule) {
    return null;
  }
}
EOF
$ gradle test
:compileJava
:processResources UP-TO-DATE
:classes
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test

MeetupTest > test_monteeth_of_may_2013 FAILED
  java.lang.AssertionError: expected:<null> but was:<2013-05-13>
```

So, it compiles for me.

Can you provide a transcript (use `script` or something?) of how it looks for you?

**Comment by jtigger** [comment]
@stkent *jinx*!!!

**Comment by robbiemacg** [comment]
@stkent @jtigger Thanks for your kind attention. I'll fetch a fresh copy of the exercise when I'm home this evening and run the tests suggested, share outputs.

When I compile code I generally do so from an exercise's main directory, so with an absolute path like, 'javac src/main/java/ExerciseName.java'. That makes it easy to run the test. Less use of 'cd -' for me.

I'll be sure to share the outputs requested this evening, but the compilation errors look to me fairly indistinguishable for what one would see if a class/package hadn't been imported. In the case of the 'meetup' exercise that means errors for every instance of 'FIRST', etc. appearing in the code, with a little caret pointing to the occurrence, line number in parens, the usual.

**Comment by jtigger** [comment]
@robbiemacg oooooohhhhh!  I now see what's going on!

You're using the Java compiler, directly and not using Gradle to manage your build!! :)  Here's a little bit of what Gradle buys you: not having to even think about a classpath.

By default, your classpath will include both your current working directory and some system JARs.  The way you're doing it, the compiler is looking for the enumeration at the root of the project (e.g. `meetup`) instead of the base directory of the Java sourceset (`meetup/src/main/java`).

You'll learn lots about how the Classpath works if you pursue this approach!  And I'd be plenty willing to support you going that route.  However, all that frustration you feel will completely fall away if you simply use Gradle.  You need to know one thing:

`$ gradle test`

full stop.

:)

**Comment by robbiemacg** [comment]
Hold the phone! So, I don't have to compile my code before issuing the 'gradle test' command? This is, literally, a revelation.

I'm sorry to have posted an issue over such a trivial misunderstanding.

**Comment by jtigger** [comment]
Nope @robbiemacg !  No such thing as a bad question.  Glad that this smoothes out the future, man.
