### ISSUE TITLE
Ensure there are enough "good first patch" issues for new-to-track contributors

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#220]
When this issue is open, it means that we need to create more issues.

At any given time, we would like between 10-20 open issues with the label "good first patch".  This makes for easy pickings for anyone wanting to try their hand at contributing to the track.

Here's that backlog:
https://github.com/exercism/xjava/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+patch%22

When:
- that list is fewer than 10, whenever you see a little thing that needs to be addressed, rather than do it yourself, capture it in one or more bite-sized issues.  Be sure to label it "good first patch".
  - if this issue is closed, re-open it... it's our semaphore that issues need to be created.
  - you can even consider it one of the many things you do in maintaining the track.
- that list is more than 20, feel free to take care of nips-and-tucks since we have plenty of runway.
  - if this issue is open, close it... it's our semaphore that no more issues are needed.

----
Maintainers: [the issues list _without_ "good first patch"](https://github.com/exercism/xjava/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20-label%3A%22good%20first%20patch%22%20)

**Comment by jtigger** [comment]
Heads-up, @exercism/java!  Here's something to be aware of.  As of right now, the "good first patch" issue count is 8.

**Comment by jtigger** [comment]
@FridaTveit has been *prolific*!!!  She has single-handedly emptied our "Good First Patch" backlog! :)  Go @FridaTveit!

**Comment by jtigger** [comment]
26 days later, @FridaTveit continues her *prolificness*, single-handedly nearly filling-up our "Good First Patch" backlog!!!  Go @FridaTveit!

**Comment by jtigger** [comment]
@exercism/java — we're at 11.  Keep scooping those little wins to this backlog!

**Comment by jtigger** [comment]
@exercism/java — Whew!  we got cleaned out!  Thanks for doing your best, @FridaTveit at trying to refill that backlog!!!

**Comment by jtigger** [comment]
See also: https://github.com/exercism/xjava/pull/338#issuecomment-283614849

**Comment by jtigger** [comment]
@exercism/java — Current count is 19!!!

**Comment by stkent** [comment]
I'm going to close this issue now we have a centralized policies document. That document links back to this issue if we ever need to pull it back up for reevaluation!
