### ISSUE TITLE
linked-list: pick implementation names that don't collide with JDK classes

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#231]
`linked-list`'s test instruct the practitioner to implement a class named `Deque`.  There's [an interface in the Java Standard Library of the same name](http://docs.oracle.com/javase/7/docs/api/java/util/Deque.html).

I entertained the notion of expecting the practitioner to implement that interface, but there are close to 30 methods.  That's a non-starter.

What's a better name for `Deque`?

**Comment by stkent** [comment]
Per http://docs.oracle.com/javase/7/docs/api/java/util/Deque.html:

> The name deque is short for "double ended queue" and is usually pronounced "deck".

So we could go verbose and use `DoubleEndedQueue`?

**Comment by NobbZ** [comment]
But as far as I remember that exercises read me does require to write a doubly linked list which is quite different from a double ended queue.

**Comment by jtigger** [comment]
@NobbZ said:
> But as far as I remember that exercises read me does require to write a doubly linked list which is quite different from a double ended queue.

Isn't a double-linked list a mechanism and the queue a policy?  That is, I can implement a queue with all kinds of storage structures: an array, a singly-linked list, a doubly-linked list, a hash table.  It's that I provide an interface over the data structure that ensures [FIFO](https://en.wikipedia.org/wiki/FIFO).

**Comment by jtigger** [comment]
@stkent said:
> So we could go verbose and use `DoubleEndedQueue`?

(this might have been @NobbZ's point) Would it be more helpful to choose a more general name like `DoublyLinkedList`? Or is naming a use of the data structure enriching?

**Comment by stkent** [comment]
Ah, I see... in this case, I'd +1 moving to a name that does not leak (or suggest) implementation details.

**Comment by jtigger** [comment]
@NobbZ, do you have a suggestion?

**Comment by NobbZ** [comment]
Well, when we did a similar exercise in OOP classes, we just called it
`List`.

John Ryan <notifications@github.com> schrieb am Sa., 31. Dez. 2016, 16:22:

**Comment by jtigger** [comment]
http://www.se-radio.net/2016/12/se-radio-episode-278-peter-hilton-on-naming/

**Comment by jtigger** [comment]
@NobbZ said:
> Well, when we did a similar exercise in OOP classes, we just called it `List`.

Well, then we'd unfortunately have *additional* problems that we've got a class (or interface, rather) of the same name *and* it's become ambiguous.

I'm seeing [rough consensus](https://en.wikipedia.org/wiki/Rough_consensus) with `DoublyLinkedList`.

**Comment by jtigger** [comment]
Created issue; the question is considered closed.
