### ISSUE TITLE
palindrome-products: is interface complexity intrinsic?

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#232]
`palindrome-products`'s interface contains a number of complex elements:

- palindromes are returned as a compound collection: `SortedMap<Long, List<List<Integer>>>`.
- the consumer must extract the outputs from the output, by hand.
- that compound collection interface forces the program to mix metaphors: `palindromes.firstKey()` and `palindromes.lastKey()`.
- the [Builder pattern](https://en.wikipedia.org/wiki/Builder_pattern) is employed to construct the result when there appears to be one actual input and it's mandatory: the number of digits in the inputs.

Are these complexities intrinsic to the problem at hand?

> find the pair of products of n-digits that yields the largest palindrome

Are there ways to address these complexities so that the practitioner either a) does not have to handle them or b) can take it one piece-by-piece?

**Comment by ErikSchierboom** [comment]
Well, I think the builder could quite easily be replaced with two parameters: one for the minumum and for the maximum factors. The sortedmap is something you have to get to know, but that's also one of the great things about these exercises: you get to know new stuff.

Overall, I was only slightly taken back by the builder pattern, which seems a bit unnecessary. The rest of the exercise was fine.

**Comment by jtigger** [comment]
Thanks for the review, @ErikSchierboom, captured as a to-work-on issue.
