### ISSUE TITLE
Phone-number: Throw exception, instead of "0000000000"?

### ISSUE THREAD

**Issue by colin-mullikin** [exercism/xjava#252]
This is more of a question than an issue, but it could spawn a workable issue.

Currently, in the phone-number exercise, if the input is invalid (less than 10 digits, 11 digits w/o starting with 1, or more than 11 digits), the expected return is "0000000000". Wouldn't it be better practice to throw some sort of InvalidArgumentException (or similar), instead of garbage data? 

This seems especially needed since there is no rule in the exercise that prohibits 000-000-0000 from being a valid phone number.

**Comment by jtigger** [comment]
👍 

And the [canonical data set](https://github.com/exercism/x-common/blob/master/exercises/phone-number/canonical-data.json) is silent on this point.

I really appreciate your nitpicks, @colin-mullikin!  These are exactly the kinds of nips & tucks that, in sum, add up to a smoother, more pleasant experience.

**Comment by stkent** [comment]
I wouldn't say that the canonical tests are silent, exactly; they suggest a null return value which is (as @colin-mullikin points out) _quite_ different from returning `"0000000000"`! If we on the Java track were to decide between `null` and a thrown exception as a better 'failure' mechanism, I think my preference would be to throw an exception (similarly to how [libphonenumber behaves](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2818) when parsing fails).

**Comment by colin-mullikin** [comment]
If we go the exception route, the next question is: when should said exception be thrown? The invalid input is given in the constructor for the PhoneNumber class, so it seems the constructor should throw it; however, that forces the user to do their processing in the constructor (which is how I solved the exercise) versus the subsequent calls, `getNumber(), getAreaCode(), pretty()`

**Comment by matthewmorgan** [comment]
+1 for throwing an exception, and +1 more for doing it as early as possible.

**Comment by colin-mullikin** [comment]
I plan on looking at this tonight, and will write the tests such that an exception is expected from the constructor. If there are any other tweaks anyone would like, let me know.
