### ISSUE TITLE
hamming: use JUnit's @Rule feature

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#262]
We've been migrating to using JUnit's [ExpectedException](http://junit.org/junit4/javadoc/4.12/org/junit/rules/ExpectedException.html) `@Rule` feature instead of `@Test(expected = SomeException.class)`. Change the occurrences of `@Test(expected = SomeException.class)` in HammingTest to make them use the `@Rule` feature instead.

**Comment by odzeno** [comment]
Will be taking this issue, and probably all the other easy ones in the next days.
