### ISSUE TITLE
nucleotide-count: use JUnit's @Rule feature

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#264]
We've been migrating to using JUnit's [ExpectedException](http://junit.org/junit4/javadoc/4.12/org/junit/rules/ExpectedException.html) `@Rule` feature instead of `@Test(expected = SomeException.class)`. Change the occurrence of `@Test(expected = SomeException.class)` in NucleotideTest to make it use the `@Rule` feature instead.

**Comment by odzeno** [comment]
and this one
