### ISSUE TITLE
allergies: remove redundant array creation

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#275]
All instances of `Arrays.asList(new Allergen[]{Allerge.EGGS, Allergen.PEANUTS, ...}` can be changed to `Arrays.asList(Allergen.EGGS, Allergen.PEANUTS, ..)`. Also, if there's only one allergen in the list it can be changed to `Collections.singletonList(Allergen.EGGS)`.

**Comment by odzeno** [comment]
I'll take this one
