### ISSUE TITLE
anagram: test names and order a bit confusing?

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#279]
After recently having done the anagram exercise, I found some of the test were in a slightly strange order with the names not being very consistent. Of the first few tests we have `testSimpleAnagram` and `testDetectMultipleAnagrams`. After that there are tests for other things such as duplicates, and same word is not anagram and so on. But then at the end of the class we have `testDetectAnagram` and `testMutipleAnagrams`. These are not the same as the first two (they use different words) but they are very similar which makes it confusing that they come right at the end. So my question is:
- Should we reorder the tests so that these four tests come right after each other?
- Should we try and rename some of these four exercises so that it is more clear how they are different (e.g. `testDetectSimpleAnagram`, `testDetectLongerAnagram`, `testDetectMultipleAnagrams` and `testDetectMultipleAnagramsOutOfLongerList`)?
- Should we try and be consistent about whether we use `detect` in the test names or not?

Also, the tests don't use all the [canonical data](https://github.com/exercism/x-common/blob/master/exercises/anagram/canonical-data.json). Is this something which should be fixed?

**Comment by jtigger** [comment]
- yes;
- yes;
- aaaaaand, yes!

(and yes).

:)

While we're at it, since the experience is fresh in your mind, if reordering the tests help create a more natural TDD flow.  That is: that if a prior test really forces the practitioner to _also_ address a subsequent test, better to put that second test, first (did I explain that clearly?).

**Comment by FridaTveit** [comment]
Yes, I think I know what you mean :) Great, I'll make a PR for this then :)

**Comment by stkent** [comment]
Resolved by #285!
