### ISSUE TITLE
hello-world: update tutorial to account for emptyStringIsComparedByValue()

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#282]
`hello-world` contains a blow-by-blow tutorial.  We recently added a test case to help catch folks using the equals operator to detect an empty string (i.e. #280).

The tutorial needs an adjustment:

- the section titles assume there are three test cases; there are now four.
- this (new) second test needs some crisp explanation about the difference between comparing by value vs. comparing the reference without invoking too many concepts.
- the tutorial avoids the pitfall of using `==` for string comparison, let's keep that; this is about clarifying _why_ this test matters.
- the audience of the tutorial are Early Programmers — people who are relatively newish to programming, but this is not their very first attempt at writing code.

**Comment by stkent** [comment]
FYI in light of https://github.com/exercism/x-common/issues/520 we may want to hold off on this change.

**Comment by jtigger** [comment]
doh!!!!  :)  Man, there goes many hours of effort into the rubbish bin. :-}

**Comment by jtigger** [comment]
Okay... the tutorial, as is, will serve as inspiration as we flesh-out the early part of the track.

- `hello-world` is/will be greatly simplified.
- looking at the current difficulty graph, we probably need to smooth that ramp out with some well-known early exercises.
- this tutorial could then be spread out across those exercises.

In light of that, this issue is no longer valid.
