### ISSUE TITLE
meetup: change test names to camel case

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#290]
Change test names in MeetupTest to [camel case](https://en.wikipedia.org/wiki/Camel_case) to be consistent with other tests and example solutions.

**Comment by odzeno** [comment]
Hey, first time contributor here!
Is it okay if I take this issue?

**Comment by stkent** [comment]
@odzeno, certainly. Thank you for checking, and (in advance) for your contributions!

**Comment by FridaTveit** [comment]
Fixed in PR #291, thanks @odzeno! :)

**Comment by odzeno** [comment]
thank you :D !
