### ISSUE TITLE
In CI, Journey Test failing to iterate over exercises

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#292]
When I run `bin/journey_test.sh` locally, it works perfectly.

However, reviewing the logs in Travis, in the `solve_all_exercises()` function, the for-loop that would iterate over the exercises simply does not execute... as if the `exercises` variable were empty.

**Comment by jtigger** [comment]
Hey @FridaTveit, I suspect you did everything right and that there's something different in the Travis CI environment.  Since you were in here last, you get dibs at taking point tackling this.  Of course, lean on the group if it gets hairy.  We're all in this together. ;)

**Comment by FridaTveit** [comment]
Okay, will have a look! :)

**Comment by FridaTveit** [comment]
It looks like it's happening because `--join-output` isn't a `jq` option in the version of `jq` being run... will look into finding another option to use. Is there a way of finding out which version of `jq` it's running?

**Comment by FridaTveit** [comment]
Or is it possible to update the version of `jq` it's running, @jtigger?

**Comment by stkent** [comment]
Travis looks to have a global version (not sure what that is), but I wonder if we could override that with a `before_install` instruction?

https://docs.travis-ci.com/user/installing-dependencies/

**Comment by jtigger** [comment]
> Is there a way of finding out which version of jq it's running?

One trick I like is to put a little bit in the build script that tells each tool used which version it is.  Something like `jq --version`.  With that in the script, it is included in the build output.  In fact, would have been a good thing to have in there in the first place. :)

> Or is it possible to update the version of jq it's running, @jtigger?

Yeah, unless there's some restriction about pre-installed tools, sounds like the tack @stkent is suggestion is a good angle.  Give it a whirl!

**Comment by FridaTveit** [comment]
Okay, so what exactly do I need to add to .travis.yml (assuming that's where I need to add it)? `sudo apt-get -y install jq`? And is there any other way of testing that it works other than making a PR and checking the travis logs?

**Comment by stkent** [comment]
That install command looks good to me! And yes, since this issue is specific to the Travis environment, I think testing by opening and modifying a PR is probably the best option :)

**Comment by jtigger** [comment]
Great question.

Yup, that's the right file: `.travis.yml`!

Personally, I'd look to see if adding `jq` to the `addons` section would install a newer version.

```
addons:
  apt:
    packages:
      - tree
```

Yeah, one great way to do this is to enable Travis for your personal account and then on your fork of `xjava`.  You'll find a bank of switches in your "Accounts"/"Profile" page.

Once enabled, you'll see that Travis builds even your branches.  So you can continue to do your work on a branch as you normally do.  When you push to your own repo, Travis kicks off the build on that branch.

**Comment by jtigger** [comment]
@stkent: *jinx*!

**Comment by stkent** [comment]
@FridaTveit listen to @jtigger not me 😄

**Comment by jtigger** [comment]
hehehehehe!  All good advice, 'round. :)

**Comment by FridaTveit** [comment]
Okay, will try that! Thanks :)

**Comment by FridaTveit** [comment]
I tried both but neither worked :( It seems like it's the linux version which is out of date. It does update `jq` but even after updating it's still version 1.4 which is the one that doesn't work...

Setting up travis on my fork worked though, I like that :)

**Comment by FridaTveit** [comment]
Any idea what else I could try @jtigger, @stkent?

**Comment by jtigger** [comment]
> Setting up travis on my fork worked though, I like that :)

Sweet!  Yeah, always nice to have ways of shortening that feedback loop on changes.  Being able to have a little personal "workspace" is great.

I'm digging into this a little bit, this morning.  I learned:

- the version of `jq` available from the official package repo for the version of Linux Travis is running for the CI builds is version 1.2 (!?!?) :( :( :(
- one of the "beauties" of Linux is... if I can't find a pre-built version of the package, we _can_ build it from source, ourselves !!! :)
  - go to https://stedolan.github.io/jq/download/ and scroll to "From source on Linux, OS X, Cygwin, and other POSIX-like operating systems"
  - for me, this is usually an _incredibly_ painful process of slogging my way through build failures manifesting as super confusing messages.  Delightfully, `jq` just built, the first time on Travis' CI box!!! 🎉 
- to get our build to pick-up this hand-built version of `jq`, we need to update the `PATH` environment variable to give _our_ version of tools preference.  To update the `PATH` on Travis CI, you need to [include a line in the `before_script` section](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Projects-from-Source).

@FridaTveit, could you please review #309?

**Comment by FridaTveit** [comment]
Great, thank you! It works! :D I did have a look at that section of [https://stedolan.github.io/jq/download/](https://stedolan.github.io/jq/download/) before, but I wasn't sure whether that was something we were allowed to do. But it all works now so happy days :D
