### ISSUE TITLE
remove one liner choco install for windows

### ISSUE THREAD

**Issue by NobbZ** [exercism/xjava#295]
Outdated magic install oneliners for choco tend to get out of date, thats why we concluded to remove the global `choco` installation instruction from the cli in exercism/exercism.io#3231 and simply link the choco installation instruction instead.

Also I want to make clear, that choco often causes trouble when run from `cmd` instead of `powershell` unless "prefixed" by `@powershell`.

Therefore I suggest to omit that current oneliner and instead tell the student to "install `choco` as described on their webpage (link) unless done already for the CLI" or something similar.

I do suggest explicitely mentioning the CLI, since it will probably be the first contact to exercisms tool chain and thats why I assume `choco` a given fact on windows for anyone who wants to do exercism.

**Comment by stkent** [comment]
I assume this was prompted by https://github.com/exercism/xjava/issues/294? Just linking for reference :)

**Comment by NobbZ** [comment]
Well, that has been the cause why I looked up your installation instruction, yes :) But since this one is about installing `choco` and the other one about installing `gradle` they are only loosely coupled, if at all ;)

**Comment by stkent** [comment]
Haha, gotcha, makes sense!

**Comment by jtigger** [comment]
So, to be clear, @NobbZ, do the instructions at http://exercism.io/languages/java/installing#windows no longer work?

**Comment by NobbZ** [comment]
Dunno and I do not even care, but I know that they might happen to fail at some time without any warning. This might have one of the following consequences until catched and changed:

* Students fail to install choco and leave either the Java track or exercism at all
* Students fail to install choco and join the chat asking for help, but it might be hard to help them out because the system might already be in a bad state which needs to be repaired before actually beeing able to reinstall choco (BTDT!)
* Students fail to install choco and open a ticket here or at exercism/exercism.io or whatever repository they think it suites to, which would have the same consequences as in the chat, but probably much slower since the issue tracking system is an asynchronous medium.

The first bullet point is bad for exercism, who wants that students turn away because of some third party tool unrelated to exercism?

The second and third bullet points might put a lot of a burden and workload that wanted to work on implementing their track, contributing to a track or even doing their own exercises while hanging out in the chat/issue tracking system. Believe me, there have been many hours gone in gitter for choco installation support before simply pointing to their instructions. After that change has been deployed, there were much less questions about some half-baked choco installation. Only thing we had to do since then was to remind people to adjust their `PATH` to have it contain the bin-stub-directory.

**Comment by jtigger** [comment]
I hear your concern that _very bad things_ can just _suddenly_ start to happen as a result of the installation instructions for Chocolatey quietly changing.

Also, I'm of the impression that both you and @kotp take the brunt of that sudden work as you are consistently providing technical support.  And that this takes up a bunch of your time in trying to help steer people in the right direction.

Am I hearing you right?

...

There's an assumption that I'd like to explore: that there's no other way to both provide a light-weight way of getting our practitioners through this setup step, reliably other than to just point them to the website.  Baked in there is a second assumption: that the UX that https://chocolatey.org/install presents is suitable for the folks getting started with Exercism.

I'm personally not impressed with the latter.  I'm wondering if we can expand our options on the former...

**Comment by jtigger** [comment]
Per #348, we've confirmed that these instructions are still working like a champ!

In the name of a thin-thread path to getting to code (i.e. minimizing how much the new-to-the-track practitioner needs to learn to get started), we're going to continue to own this one step in the process.  When there are demonstrated systemic issues, that's a great time to revisit this.

**Comment by jtigger** [comment]
Captured as an official "policy" in #395.
