### ISSUE TITLE
heads up: strain and accumulate are scheduled for deprecation

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#297]
[strain](https://github.com/exercism/x-common/issues/588#issuecomment-279275431), [accumulate](https://github.com/exercism/x-common/issues/553#issuecomment-279275406)

Wasn't sure of the best way to raise awareness of this otherwise. We should focus efforts on other exercises in lieu of improving these ones.

**Comment by jtigger** [comment]
I see you're keeping an eye on x-common discussions!  This is a really valuable thing to do! ;)  Katrina is making a real go at delegating.  There's a number of "Task Forces" that have kicked off and are clearly in full-stride in cleaning up the curriculum part of the platform.

**Comment by jtigger** [comment]
So, the course of action here would be to move these exercises into the `deprecated` section in the `config.json`.  Did you want to ... fold... that in to #286 ?

**Comment by stkent** [comment]
Since list-ops is not available in this track yet (though close!), I think it would be good to keep them around a while longer?

**Comment by stkent** [comment]
Nice pun, it was not unnoticed :D

**Comment by jtigger** [comment]
> Since list-ops is not available in this track yet (though close!)

painfully so! :)  I'm so grateful to @javaeeeee's efforts there... it's really shaping up.

> I think it would be good to keep them around a while longer?

Now, there you go making sense. :)

**Comment by jtigger** [comment]
#207 has been merged!  🎉 

@stkent are you happy with the way this all unfolded (i.e. notifying the track that these two exercises were deprecated)?  Or do you think we can improve on this (e.g. literally adding in a `@Deprecated`s throughout the test suite/example)?

**Comment by stkent** [comment]
I think that leaking this information into the tests/examples would be overkill; however, deprecation being signaled by what seemed to be an somewhat-offhanded remark made by @kytrinyx in a generated issue in an upstream repository doesn't seem to be ideally visible! If there's a change to explore here, I would think it would be figuring out how to make that sort of decision more widely knowable. (There may well have been prior upstream discussion about those exercises that I missed, in which case, forgive my lack of knowledge!)

**Comment by kytrinyx** [comment]
I think I have on my todo list somewhere to generate an issue for each track about deprecation of certain exercises, but everything's been a jumble for a while and I've lost track. I think those discussions happened in the x-common repository. I apologize for the confusion. I'd love it if we could lock down good procedures around all of this.

**Comment by stkent** [comment]
Generated issues would be perfect (from the POV of an actively-maintained track, at any rate)!

**Comment by kytrinyx** [comment]
I found:

- https://github.com/exercism/discussions/issues/40
- https://github.com/exercism/x-common/issues/279
- https://github.com/exercism/x-common/issues/129

I'll update the discussions one to ask if someone wouldn't mind taking charge of figuring out exactly what has been decided, and what still needs to be done, and making it so.

**Comment by stkent** [comment]
@kytrinyx  ❤️  thanks for doing that digging and centralizing!

**Comment by stkent** [comment]
I notice that none of those issues mention `strain` being deprecated in favor of list-ops; is https://github.com/exercism/x-common/issues/588#issuecomment-279275431 the canonical reference for that decision? If so I'll add it to https://github.com/exercism/discussions/issues/40 for reference.

**Comment by kytrinyx** [comment]
Excellent find. I think that the comment you're referring to is the canonical reference (as much as we have one, anyway!)

**Comment by stkent** [comment]
Roger that; adding to https://github.com/exercism/discussions/issues/40 as promised!
