### ISSUE TITLE
nucleotide-count: fix spelling mistakes in test names

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#306]
Change the test names in NucleotideTest so that they use the correct nucleotide names: adenine, cytosine, guanine, and thymine.

**Comment by FridaTveit** [comment]
Fixed in PR #307. Thanks @extrika! :)

**Comment by extrika** [comment]
You're welcome! My first contribution to an open source project!

**Comment by stkent** [comment]
@extrika that's awesome! :)

**Comment by jtigger** [comment]
Congratulations, @extrika!

Now that you're on _this_ side of the experience, we'd love to hear about your experience in getting here.  Are there parts of any instructions that were wrong or confusing?  Did you have to overcome any challenges outside of the code fix itself?

**Comment by extrika** [comment]
I guess the challenge for a beginner is becoming comfortable with git and GitHub. I used the HelloWorld guide from  GitHub to become familiar with the 'fork/branch/commit/pull request" workflow. The documentation from the exercism repo is clear and I must say that I'm impressed by the human contact! I love the exercism project and I look forward to contributing in any way I can.

**Comment by extrika** [comment]
Any tips or common mistakes to avoid for a beginner?

**Comment by jtigger** [comment]
Thanks for your reflections @extrika!  That is valueable to know!

Personally, I think you've already avoided the big mistakes: trying too hard to make the aubmission perfect without review; conversely, not caring about the details.

**Comment by extrika** [comment]
Thanks!
