### ISSUE TITLE
How do we tend to this garden?

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#319]
With #142 we took a big step in making this track more approachable.... or did we?

This question-issue is an invitation to pause and reflect on the (honestly, great) work we're doing and making sure we have a shared sense of direction...

----

Grab one of these questions (or add your own) and explore out loud in this issue:

- How do we know that the "improvements" we are making are making improvements?  (in other words, what ways can we measure the "health" of this track and/or the effect of a change we've made?)
- What are we aiming for?  What, exactly, is "better?"
- One thing we can do, as maintainers, is add new exercises.  What other actions can we take (both in this repository and on the live track, itself)?

attn: @exercism/java

**Comment by jtigger** [comment]
> What other actions can we take?

I see @FridaTveit doing her level best to identify and scope "good first patch" issues!  Having such a backlog is an invitation for others to contribute.  Today's contributors can become tomorrow's fellow maintainers.  👍

**Comment by stkent** [comment]
2¢

- now that we have established a rough ordering, we can start addressing issues like https://github.com/exercism/xjava/issues/177, https://github.com/exercism/xjava/issues/178 to help ease users into the language features;
- again, post-reordering, we now have exercises written at very different times in the track's maintenance history interspersed. It would probably be beneficial to run through exercises starting at the very beginning (the highest-visibility exercises) and try to improve consistency (documenting decisions along the way to help maintain that consistency moving forward);
- a sweep of all exercises to bring them in line with any changes in canonical data would be most excellent

In terms of measuring the impact of our changes; I can't think of many good ways to do that that don't require website changes, which doesn't seem to be a fruitful area to be exploring at the minute :P

**Comment by jtigger** [comment]
Love all of that, @stkent!

I also wonder, while we're making the track sweep, if we'll also want to toss in some more hints, references, and other resources along the way... some candy along the trail?

In terms of impact, we currently have this: http://exercism.io/stats/java.  The chart currently reflects the reordering but should return to a more smooth drop-off of submissions.  We can look for steep drop offs and explore if there's something about that exercise that might be deterring folks.

I also created an Exercism Team with us in it (you should have gotten an invite, please let me know if you haven't)... making it easier to see our collective activity on the site, itself.

**Comment by stkent** [comment]
Neat stats page! Worth revisiting in a week or a month, once those graphs reflect the ordering? We can perhaps compare drop-off rates before/after the reordering to see if there was a significant impact. 

I see I am in the new admins team, but again, wasn't notified! I can't see anything wonky in my Settings 😐

**Comment by jtigger** [comment]
Re: comparing drop-off rates
Yes we can.  I've slurped the json from that page, in the past and we can pull into Google Sheets to compare.

re: team membership
Not sure if I confused things but, I was referring to the team feature on exercism.io.  Although I concurrently created a new GitHub team for the active track maintainers.

**Comment by stkent** [comment]
Hah, oops, I saw and just now accepted the invite on Exercism.io. My bad!

**Comment by jtigger** [comment]
@exercism/java:
There is lots of activity on the track -- which is grand!  The aim of this discussion is to think through and establish some rough consensus around what our goals are.

Thoughts?  Questions?

**Comment by stkent** [comment]
When I look back at the goals I posited, it would seem that we're making good progress towards them; the only one we haven't worked on as much is exercise standardization and comparison to the current canonical data! I'm also wary of batch-creating issues for all that work though, since they are highly likely to become stale.

**Comment by jtigger** [comment]
Agreed.  I wonder if you've identified another kind of issue we want the probot to ignore.

But what to call that label... ?

Some adjustments might actually be "good first patch" if they are simple enough. 

If one is more involved, perhaps we've identified another sort of backlog.  A kind of "intermediate" that once you've done a "good first" or three, we'd encourage you to look at _this_ list for your next submission?

"good second patch"? :)

**Comment by jtigger** [comment]
The originating question of this issue was answered.  #555 is covering the question around configuring probot.
