### ISSUE TITLE
hello-world: when should we implement the significant changes to the canonical exercise?

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#321]
See https://github.com/exercism/x-common/pull/544/files for the relevant changes.

@jtigger how would you like to go about this? Should we hold off on this change until the hello-world replacement is fleshed out so that we can seamlessly transition the introductory content to the second exercise?

**Comment by jtigger** [comment]
There are a couple of efforts that will impact the front of the track:

1. The `hello-world` replacement
2. An effort to identify the first three exercises across tracks (which may affect which exercise is second).

However the `hello-world` replacement lands, it is hard to imagine it will be simpler than, say, `leap`.

I'm starting to think that the tutorial would actually get split over the first few exercises...

So, I'm wondering if it would be prudent to hold off until the dust settles, here.  Or, we could iterate the tutorial with each change.

Thoughts?

**Comment by stkent** [comment]
I'm cool with directing efforts into less-temporary changes until all aspects of the initial track experience are hashed out!

**Comment by stkent** [comment]
I'm going to update this issue title to reflect the actual content better.
