### ISSUE TITLE
clock: estimate difficulty and move to appropriate position within track

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#322]
The exercise `clock` was added after we'd already re-ordered the track. By default, new exercises are scored with difficulty 1 and located at the end of the track. We should use this issue to discuss and determine an estimated difficulty for `clock`, then submit an associated PR that moves `clock` to the appropriate position within the track based on that difficulty.

**Comment by FridaTveit** [comment]
I'm very bad at estimating, but maybe 7 or 8??

**Comment by FridaTveit** [comment]
This still hasn't been estimated, so the issue should probably stay open.

**Comment by stkent** [comment]
Closed by #620.
