### ISSUE TITLE
perfect-numbers: estimate difficulty and move to appropriate position within track

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#323]
The exercise `perfect-numbers` was added after we'd already re-ordered the track. By default, new exercises are scored with difficulty 1 and located at the end of the track. We should use this issue to discuss and determine an estimated difficulty for `perfect-numbers`, then submit an associated PR that moves `perfect-numbers` to the appropriate position within the track based on that difficulty.

**Comment by FridaTveit** [comment]
Maybe 3 would be an okay difficulty?

**Comment by jtigger** [comment]
Sorry for the long delay... I'm working my way through my personal xJava backlog.  Likely tomorrow (with the other estimations).

**Comment by FridaTveit** [comment]
This shouldn't be closed as we haven't estimated it yet.

**Comment by stkent** [comment]
Closed by #619!
