### ISSUE TITLE
change: estimate difficulty and move to appropriate position within track

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#324]
The exercise `change` was added after we'd already re-ordered the track. By default, new exercises are scored with difficulty 1 and located at the end of the track. We should use this issue to discuss and determine an estimated difficulty for `change`, then submit an associated PR that moves `change` to the appropriate position within the track based on that difficulty.

**Comment by FridaTveit** [comment]
This still hasn't been estimated, so the issue should probably stay open.

**Comment by FridaTveit** [comment]
@stkent you'd probably know best since you implemented it. But maybe 8 or 9? :)

**Comment by stkent** [comment]
`change` is algorithmically complex; the 'obvious' implementation (find the largest coin smaller than your total; subtract multiples of that coin until your remaining total is less than the coin value; repeat with next coin) doesn't always work. The basic premise remains recursion though. I'd say 8-9 works here; I'll add a PR with a suggested position :)
