### ISSUE TITLE
Fail fast if configlet detects that exercise is missing from config.json?

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#326]
Right now, the build continues to execute for 12-13 minutes. Would it be possible to fail faster in this case of forgetfulness? 👼

**Comment by jtigger** [comment]
Agreed!

In fact, I think there's a larger problem of where the _intent_ is to rely on the `set -e` to fail the build, but that's not always working (e.g. when an error occurs running a subshell that assigns its output to a variable in the main script).

This _should_ be happening in `unit-test.sh` (i.e. `set -e` is in the preamble), but somehow this doesn't fail the build... 💣

**Comment by jtigger** [comment]
This relates to #410.  Gonna note this point in that issue and consider this question closed: yes we want fast-failing builds!

**Comment by Smarticles101** [comment]
If anyone has any specific examples of set -e not failing the build when it should have, could you post them here? I'm going to try fixing this and play around with it a bit @exercism/java and @jtigger if you have the time

**Comment by stkent** [comment]
https://travis-ci.org/exercism/java/builds/205128042; unit tests failed but journey tests ran anyway. This was before we split them out.
