### ISSUE TITLE
ocr-numbers: estimate difficulty and move to appropriate position within track

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#341]
By default, new exercises are scored with difficulty 1 and located at the end of the track. We should use this issue to discuss and determine an estimated difficulty for `ocr-numbers`, then submit an associated PR that moves it to the appropriate position within the track based on that difficulty.

**Comment by FridaTveit** [comment]
This still hasn't been estimated, so the issue should probably stay open.

**Comment by FridaTveit** [comment]
@stkent You'd probably know best since you implemented it, but maybe 8 or 9?
