### ISSUE TITLE
hamming: adjust API to use an instance method over class methods

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#346]
As per #177, adjust the test suite to require a solution that uses an instance method instead of a class method.

_(see #344 as an example and the conversation about Function Object vs. Value Object)_

**Comment by jtigger** [comment]
In order to avoid frustrating rework, let's resolve the stylistic question posed in #344 before picking this up.

**Comment by FridaTveit** [comment]
Fixed by PR #385.
