### ISSUE TITLE
Verify that the Windows installation instructions work with Windows 10

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#348]
The instructions for installing Chocolatey were written against Windows 8.

There have been calls to point practitioners to the Chocolatey site to install that package manager (#295), but those instructions lack the conciseness needed to someone who just wants to get started with Exercism.

On either a physical machine or in a [Virtual Machine](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), please walk through the installation instructions on Windows 10.  If there is _any_ difference between what's described in the instructions, either note them here or open a pull request with the needed changes.

**Comment by superklamer** [comment]
I ran the steps on my Win 10 Enterprise. Everything worked and I did not have to do anything differently. Choco installed, Java JDK installed, Environment variables were present, Gradle installed. I was able to run some test cases. Everything seemed fine. 
I can attach screenshots if  necessary.

**Comment by jtigger** [comment]
Woohoo! 🎉   Thank you for doing this, Radoslav!  This is a big help in ensuring that our thin-thread path (designed to get practitioners into writing code as fast as possible) is legit.  Ensuring that there are not little bumps or swerves in the path is basically ensuring there's a nice welcoming red carpet.  Thank you!

**Comment by kotp** [comment]
Is there a way to automate these installation steps so that we can monitor if this breaks, rather than relying on student reports?

**Comment by jtigger** [comment]
ooooooh!  I love that, @kotp.... the tricky part would be getting an administrative shell on a CI windows box.  Definitely worth looking into!

**Comment by jtigger** [comment]
The original request of this issue was addressed with @superklamer's work (thanks again!).  Closing.
