### ISSUE TITLE
rna-transcription: what to do with the UnsupportedOperationException

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#350]
In the second exercise, `rna-transcription`, we introduce the practitioner to the idiomatic `UnsupportedOperationException`.  This is lovely in many ways.

Let's soften the introduction with a terse mention of what that exception is, what it does (i.e. causes the test to fail with that error message) and what to do about it.

Do this by creating a `HINT.md` in the root of the exercise directory; the contents of that file are automatically merged into the `README.md` file delivered with the exercise.

**Comment by stkent** [comment]
hello-world now [also uses this exception](https://github.com/exercism/xjava/blob/master/exercises/hello-world/src/main/java/HelloWorld.java#L3), so we should probably retarget that instead? cc @FridaTveit for thoughts!

**Comment by FridaTveit** [comment]
Sorry, I didn't notice! That sounds like a good plan, I'll change my PR :)
