### ISSUE TITLE
accumulate: adjust API to use an instance method over class methods

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#361]
As per #177, adjust the test suite to require a solution that uses an instance method instead of a class method.

_(see #344 as an example and the conversation about Function Object vs. Value Object)_

**Comment by stkent** [comment]
Reminder, accumulate is deprecated :)

**Comment by jtigger** [comment]
oh yeah, totally forgot... just blindly combing through the track.  Thank you!
