### ISSUE TITLE
robot-name: avoid test pollution

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#362]
The exercise `robot-name` creates a single instance of `Robot` to be used for all test methods instead of creating a new instance for each test method.  This structure assumes that instances of `Robot` cannot have state beyond what `reset()` clears; there's no need to do so.

Please move this initialization to a [`setUp()`](http://junit.sourceforge.net/javadoc/org/junit/Before.html) method.

After this is done, if you want a bigger challenge, see #61.

**Comment by superklamer** [comment]
Submitted #391
