### ISSUE TITLE
strain: include hints to explain why methods are static

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#367]
As per #177, we prefer using instance methods over class methods (see discussion in that issue for rationale).

However, there _are_ conditions in which it is absolutely appropriate for a function to be `static`.  A common situation is because the function is effectively an extension of an existing type — you are defining behavior you wished were defined on a given type.

Since classes in Java are closed for modification (i.e. you cannot add members to a class outside its definition like you can in other languages like Ruby or JavaScript), you cannot add the new behavior to the class, directly.  The idiomatic solution in this case is to write a utility method.

Collections of these kinds of methods are often referred to as "utility classes".  Examples of such classes from within the JRE include [`Arrays`](https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html) and [`Collections`](https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html).

In the case of the exercise `strain`, we "wish" that [`List`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html) had `keep()`, `discard()`, and `filter()` methods on it.  It doesn't, so we're including them here.

Please include a `HINT.md` file in `strain` that points out that these methods are static and capture the description above, in your own words as to why this class has this shaped API.

**Comment by stkent** [comment]
Reminder that `strain` is in the process of being deprecated in favor of `list-ops`

**Comment by jtigger** [comment]
Awwww geez!  Thank you, @stkent! :)  I'll close this and create a new one for that exercise.

**Comment by stkent** [comment]
Perfect!
