### ISSUE TITLE
grade-school: remove potential test pollution

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#371]
The `grade-school` exercise creates a single instance of `School` and uses it through the entire test suite.  The suite has deftly avoided test pollution by leaning on deterministic test ordering and using different grades in each test.  This sets a bad example of how to organize tests: each test should be isolated from the others so as to avoid false negatives (test failures when there is no corresponding defect in the code) and false positives (tests passing when a defect exists but is covered up by side-effects of earlier tests).

Please move the construction of `School` into a [`setUp()`](http://junit.sourceforge.net/javadoc/org/junit/Before.html) method.

**Comment by superklamer** [comment]
Hi jtigger, I am learning Java now and I am just starting to contribute to GitHub projects, but if you don't mind I would like to take a shot at this.

**Comment by jtigger** [comment]
I'm delighted you're digging in, @superklamer.  Your PR looks good (included some rebase help, there).  Thanks for your support!
