### ISSUE TITLE
binary-search: does the test suite represent the appropriate amount of DRY-ness?

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#372]
Does the test suite for [`binary-search`](https://github.com/exercism/xjava/blob/master/exercises/binary-search/src/test/java/BinarySearchTest.java) exhibit [chafing](https://github.com/testdouble/test-smells/tree/master/smells/unclear/chafing)?

There are a number of constants defined at the top of the test which are referenced within the suite below.  This means that when reading a particular test, I need to scroll up to see the definition of the test data.

In the link to "chafing", above, Justin Searls talks through balancing clean test code with readable test code.

Question (@exercism/java): is this test suite too DRY?  Or is it okay?

**Comment by FridaTveit** [comment]
I think it's too DRY. From trying to do the exercise now I think it makes it more confusing when I keep having to go to the top of the tests to find the actual values in the list being searched. The `LIST_OF_UNIT_LENGTH` and `EMPTY_LIST` are pretty easy to guess, but for longer lists with actual values I think it would be useful to have them repeated inside each test where they're used.

**Comment by matthewmorgan** [comment]
Hmm.  I would agree with @FridaTveit .  I feel like this test has a 'medium' level of indirection, like I'd rather see the values right in the tests, or see everything parameterized.  At the moment it is clearly written, yet still a bit hard to read.

**Comment by jtigger** [comment]
@stkent : any thoughts on this?  With no objection, I'll convert this into an actual issue.

**Comment by stkent** [comment]
I concur with everything else written here - +1 making an issue for the changes.

**Comment by jtigger** [comment]
Captured: #602.
