### ISSUE TITLE
wordy: extract common setup

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#374]
In the `wordy` exercise, every test method duplicates the construction of the instance of `WordProblemSolver`.

Please extract the construction into a [`setUp()`](http://junit.sourceforge.net/javadoc/org/junit/Before.html) method and use the instance data member instead.

**Comment by vasouv** [comment]
Hi! Can you assign me for this one?

**Comment by FridaTveit** [comment]
You can just start working on it if you like :) As long as you've commented on here other people should know not to start working on it as well :)

**Comment by jtigger** [comment]
Agreed with @FridaTveit.  Also: https://github.com/exercism/xjava/issues/343#issuecomment-287791015.

**Comment by FridaTveit** [comment]
Fixed in PR #387 :)
