### ISSUE TITLE
sublist: extract common setup

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#375]
In the `sublist` exercise, every test method duplicates the construction of the instance of `RelationshipComputer`.

Please extract the construction into a [`setUp()`](http://junit.sourceforge.net/javadoc/org/junit/Before.html) method and use the instance data member instead.

**Comment by stkent** [comment]
@jtigger these instances are not all set up identically, since they use generics. What would you like to do here given that new information? :)

**Comment by jtigger** [comment]
Nope, this was a [bad miss](https://www.youtube.com/watch?v=ZK1HlsISs78) on my part.  Closing.
