### ISSUE TITLE
Adjust CI build to detect when an exercise test suite omits the org.junit.Ignore import.

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#389]
_(First detected as part of #388 ... nice catch @stkent !)_

Today, the CI build removes all `@Ignore` annotations from tests before running tests so that those tests can be verified to work (at least with the example code).  However, this modification of the test suite covers a rare but not-so-nice bug in the test suite: if we omit the `import org.junit.Ignore;` at the top of the test suite, we don't detect this.  When the practitioner downloads the exercise, they'll run the build and it won't compile, complaining of a missing import!

Please review the CI process and determine how best to detect this case.  We're looking to minimizing how much complexity we add to the build... do your best to avoid making this a one-off case.

**Comment by stkent** [comment]
I have an idea for this once I can run the exercise tests locally :)

**Comment by jtigger** [comment]
Nice! ... and then, gak!  Okay, #394 is on my list.
