### ISSUE TITLE
In "Installing Java" instructions, minimize the length of the onramp.

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#395]
The Installing Java instructions should seek to minimize the number of steps and the number of concepts a new-to-the-track practitioner needs to learn to get to coding.

An example of this came up in #295.  Linking to the Chocolatey site for installation instructions was tantamount to tossing the practitioner in the deep end of the pool; those instructions were not context-free and not easy to follow.  In contrast, we found a simple one-liner that has been verified (#348) on the latest version of the OS (and had been previously tested on earlier versions).

**Comment by superklamer** [comment]
If you are thinking of just combining all steps into one. I am pretty sure we can set up a PowerShell script that does all that and checks for the exit code of the installs to make sure everything is installed correctly. I am thinking of something that either has command line switches (-choco -jdk8 -gradle), or just gives the user option on what to install at the beginning.

**Comment by jtigger** [comment]
Ah!  Well, yeah, there needs to be a balance...

The balancing "force" is that we'd also like to minimize in how much "magic" occurs too.

If they are tools you should be aware that they exist (like Gradle and the JDK), I believe it's worth the experience of doing the install.

The lower-level details (such as what environment variables need to be set, OS path, etc) actually become a real pain/distraction without adding any real value for the new-to-the-platform person.

**Comment by FridaTveit** [comment]
Closing this issue as it has been included in the POLICIES doc :)
