### ISSUE TITLE
binary-search-tree: replace lambda with method reference

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#407]
Two tests in binary-search-tree (`createsComplexTree` and `iteratesOverComplexTree`) use the [lambda expression](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html) `value -> sut.insert(value)`. This could be simplified to the [method reference](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html) `sut::insert`.

**Comment by Smarticles101** [comment]
I'll do this one

**Comment by FridaTveit** [comment]
Fixed in PR #497 :)
