### ISSUE TITLE
book-store: Example implementation is incorrect

### ISSUE THREAD

**Issue by behrtam** [exercism/xjava#416]
The description of the exercise describes a a scenario that is also a [test case](https://github.com/exercism/xjava/blob/master/exercises/book-store/src/test/java/BookstoreTest.java#L70-L74) where two groups of 4 are cheaper than two groups of 5 and 3. The example implementation always starts with the biggest possible group and does not try all other combinations to really find the cheapest price.

The problem why the tests don't find this is the incorrect use of the delta parameter in the assert method.
```java
List<Integer> books = new ArrayList<>(Arrays.asList(1,1,2,2,3,3,4,5));
Bookstore bookstore = new Bookstore(books);
assertEquals(51.20,bookstore.calculateTotalCost(),2);
```

While `calculateTotalCost()` actually returns the wrong price of `51.6` because of the `delta=2` even `53.2` or `49.2` would be considered equal.

> delta - the maximum delta between expected and actual for which both numbers are still considered equal. 

Maybe `delta` should better be something like `0.001` so people really implement the correct algorithm.

**Comment by stkent** [comment]
Ooh, good spot, thanks for the report!
