### ISSUE TITLE
isogram: estimate difficulty and move to appropriate position within track

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#432]
By default, new exercises are scored with difficulty 1 and located at the end of the track. We should use this issue to discuss and determine an estimated difficulty for `isogram`, then submit an associated PR that moves it to the appropriate position within the track based on that difficulty.

**Comment by FridaTveit** [comment]
Maybe estimated difficulty 4?

**Comment by stkent** [comment]
I'd concur; example implementation is pretty short and not too involved. Let's throw it on the back end of the 4s for now, to play it safe; then to refine, we can compare with the exercises either side and argue for swapping up/down if needed. (In fact, I think that's the easiest way to grok sorting something as big as the collection of exercises from now on (comparison to direct neighbors, and swapping if necessary)).
