### ISSUE TITLE
book-store: estimate difficulty and move to appropriate position within track 

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#433]
By default, new exercises are scored with difficulty 1 and located at the end of the track. We should use this issue to discuss and determine an estimated difficulty for `book-store`, then submit an associated PR that moves it to the appropriate position within the track based on that difficulty.

**Comment by FridaTveit** [comment]
@exercism/java maybe 8?

**Comment by stkent** [comment]
👍 again, algorithmically non-trivial.
