### ISSUE TITLE
Add hint to remaining @Ignore annotations

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#448]
Add a hint with the value "Remove to run test" to the `@Ignore` annotations that aren't covered by the good first patch issues:

- [x] pangram
- [x] gigasecond
- [x] space-age
- [x] acronym
- [x] difference-of-squares
- [x] secret-handshake
- [x] matrix
- [x] triangle
- [x] largest-series-product
- [x] sieve
- [x] twelve-days
- [x] nth-prime
- [x] diamond
- [x] isogram
- [x] flatten-array
- [x] phone-number
- [x] accumulate
- [x] nucleotide-count
- [x] word-count
- [x] robot-name
- [x] allergies
- [x] bob
- [x] pascals-triangle
- [x] bracket-push
- [x] series
- [x] atbash-cipher
- [x] beer-song
- [x] queen-attack
- [x] etl
- [x] linked-list
- [x] grade-school
- [x] robot-simulator
- [x] binary-search
- [x] minesweeper
- [x] wordy
- [x] all-your-base
- [x] anagram
- [x] sublist
- [x] binary-search-tree
- [x] rectangles
- [x] meetup
- [x] crypto-square
- [x] simple-cipher
- [x] palindrome-products

See issue #426 for discussion.

**Comment by mraediaz** [comment]
Will be working on `linked-list`.

**Comment by FridaTveit** [comment]
All of these are currently done or in review :)

**Comment by stkent** [comment]
@FridaTveit awesome work! I think this issue can be closed now?

**Comment by FridaTveit** [comment]
Looks like it :)
