### ISSUE TITLE
Add Java version requirements to track

### ISSUE THREAD

**Issue by pietvandongen** [exercism/xjava#45]
For example, some problems require Java 8 to be solved.

**Comment by kytrinyx** [comment]
Should we say which problems require which versions of Java, or just put a blanket statement that Java 8 is required?

**Comment by pietvandongen** [comment]
I think it would be best to say so, yes. The downside is that some might have to install it first, but Java 8 isn't super new and some exercises can't be solved without it (the tests use classes only found in Java 8).

**Comment by kytrinyx** [comment]
Ok, thanks. I've updated the docs site with this.

**Comment by pietvandongen** [comment]
Thanks!
