### ISSUE TITLE
acronym: add test case for all caps within mixed case word

### ISSUE THREAD

**Issue by chuckwondo** [exercism/xjava#520]
@weibeld [pointed out to me](http://exercism.io/submissions/39efa19c768a44fbbf671833581c975b) that although my acronym solution passes all current test cases, it will not work for the word/phrase `SuperHTMLParser`. The correct acronym is `SHP`, not `SH` as given by my earlier solution.

I suggest we add `SuperHTMLParser` to the test suite, with the expected acronym value of `SHP`.

**Comment by jtigger** [comment]
Solid catch!  @chuckwondo would you mind posting this to the x-common repo?  All exercises have a common set of test metadata (i.e. JSON of the test cases).  You'll also get all the eyeballs of folks on the many other tracks too.

**Comment by chuckwondo** [comment]
See https://github.com/exercism/x-common/issues/787.

**Comment by stkent** [comment]
The upstream issue created by @chuckwondo led to an interesting discussion that was [eventually resolved](https://github.com/exercism/x-common/pull/788) by removing the only existing test case for a phrase that included a PascalCased word (`HyperText Markup Language`). I believe that the example phrase in this xjava issue (`SuperHTMLParser`) can now be considered out of scope for this exercise, and clarification of that fact will occur when the exercise is made compliant with v1.1.0 or later of the canonical data. Closing, but please feel free to reopen this issue if I've misunderstood anything!
