### ISSUE TITLE
scrabble-score: add additional test case with non-word chars

### ISSUE THREAD

**Issue by weibeld** [exercism/xjava#524]
I propose to add the following test case to the [tests](https://github.com/exercism/xjava/blob/master/exercises/scrabble-score/src/test/java/ScrabbleScoreTest.java) of `scrabble-score`:

```java
{"Hello, world!", 17}
```

This case contains printable non-word characters and whitespace within the string.

There is currently another test case with non-word characters:

```java
{" \t\n", 0}
```
However, this case consists of only whitespace characters, and I noticed that many submissions simply use `trim()` on the string to make the test pass. With my proposed test case, this wouldn't be possible anymore and programmers are stimulated to use a more robust approach to sort out undesired characters.

**Comment by chuckwondo** [comment]
Further, I suggest that test cases that include non-word chars expect an `IllegalArgumentException`, not that they expect the non-word chars to be ignored/skipped.

Of course, the extra credit problems for letter- and word-multiplier squares might make that problematic, but there is no indication of how such multiplier squares might be represented as part of the input.

**Comment by stkent** [comment]
I just opened a PR to update the xjava implementation of this problem to match the [current canonical test data (v1.0.0)](https://github.com/exercism/x-common/blob/11ed5039054a84b58bc7ccdda250d8a0121ccbed/exercises/scrabble-score/canonical-data.json). These test cases no longer include non-alphabetical characters, so I'm going to close this xjava issue.

If either of you feel strongly that non-alphabetical characters _should_ be tested as part of this exercise, or that this exercise would benefit significantly from requiring input validation, please open a new issue in x-common to make your case! Thanks ❤️
