### ISSUE TITLE
Make first exercise in the track (Etl) start with failing tests, not compilation errors.

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#53]
Today, we start off new folks with a wrongly filled-out solution file.  I'm proposing that not only should we fix this, but provide enough code in that first exercise that when the exercist runs the tests, they get tests failing for the right reasons (i.e. on assertions) rather than compilation errors.

So, go from this:

```java
public Etl {
}
```

*(notice the missing `class` keyword; but will yield other compilation errors, too)*

...to this...

```java
import java.util.List;
import java.util.Map;

public class Etl {
    public Map<String, Integer> transform(Map<Integer, List<String>> old) {
        return null;
    }
}
```

Thoughts? (cc: @kytrinyx @pietvandongen @vdemeester @sit)

**Comment by kytrinyx** [comment]
Yeah, I think this sounds good. Then perhaps on the next exercise we can have compilation errors (and maybe warn them about it).

**Comment by vdemeester** [comment]
I also think it sound good too :wink: ; about the warning too.
