### ISSUE TITLE
Some exercises have starters with compilation errors

### ISSUE THREAD

**Issue by jtigger** [exercism/xjava#54]
In @vdemeester 's clean-up (via 8e35e87e194632a411bdb8c9351a7be6ab5408f9) accidentally included compilation errors.  Namely, that three starter classes — `Etl`, `WordCount`, and `DNA` were missing the `class` keyword.

**Comment by vdemeester** [comment]
@jtigger oh my god :sweat:, that's bad and I missed it :sob:

**Comment by jtigger** [comment]
Don't sweat it, @vdemeester.  It's easy to miss stuff.  I'm wondering what we can do to automate checks on little things like this to protect us from these little details.

Imagine a build that at least ensures that if a file exists in `src/main/java` that it at least compiles... :smile:

**Comment by kytrinyx** [comment]
Compiles... would that be just a plain `javac path/to/file.java`? Because that seems like a fairly straight-forward bash script or make script to write.

**Comment by jtigger** [comment]
Yes.  We do have some exercises with multiple starter files (e.g. `triangle` has `TriangleException.java` and `TriangleKind.java`).  At that point, with a build.gradle in place, already, the script could contain:

```bash
gradle compileJava
```

Unless someone beats me to it, I'll be hitting this up as an opportunistic improvement along with #53.

**Comment by jtigger** [comment]
Note that this check is now in place with the work done on #50.  Namely, we compile any starter code (i.e. anything in `src/main/java`) in the build script (`bin/build.sh`) which is run in CI.

**Comment by kytrinyx** [comment]
Sweeeet!
