### ISSUE TITLE
Probot: helping or hurting?

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#555]
After observing probot run for a few weeks, I'm tempted to suggest that we might want to explicitly mark internal issues (i.e. issues generated and entered by track maintainers) as exempt from becoming stale. Unlike support requests, which can hang around open if the original reporter never returns, these internal issues are meant to form a backlog of work to be tackled when availability allows. Their relevance therefore rarely expires.

Thoughts, @exercism/java?

**Comment by FridaTveit** [comment]
I agree, that sounds like a good plan :)

**Comment by morrme** [comment]
i'm not a team member but perhaps a new tag can be created for that purpose so that the probot ignore file can be configured to ignore  it?

**Comment by stkent** [comment]
Yeah, I'd thought about that too, but I think we'd end up with 95% of issues tagged with it, so if possible I'd prefer to flip it around and only have certain tags be eligible for becoming stale. Need to investigate more. Thanks for the suggestion!

**Comment by stkent** [comment]
I looked into this and there does not appear to be a way to configure probot to opt-in to specific labels :/

**Comment by stkent** [comment]
This issue tracks the feature I'm imagining: https://github.com/probot/stale/issues/22

**Comment by stkent** [comment]
While that probot feature is under construction, I propose that we temporarily disable it (by removing the `stale.yml` file. 👍/👎 @exercism/java?
