### ISSUE TITLE
simple-linked-list: replace deprecated assertEquals() and fix input parameter error

### ISSUE THREAD

**Issue by rstockbridge** [exercism/xjava#567]
Replace `assertEquals()` with `assertArrayEquals()` in the tests `canReturnListAsArray()` and `canReturnEmptyListAsEmptyArray()`. 

Also swap input parameters to correctly represent the input and expected arrays, which are currently backwards.

**Comment by FridaTveit** [comment]
Thank you for spotting this @rstockbridge! :)
