### ISSUE TITLE
simple-linked-list: unnecessary generic method

### ISSUE THREAD

**Issue by rstockbridge** [exercism/xjava#568]
I believe that the example solution unnecessarily uses a generic method when entire class is generic. Specifically it seems to me that `private <T> T[] newArray(Class<T> clazz, int size)` can be replaced by `private T[] newArray(Class<T> clazz, int size)`.

**Comment by morrme** [comment]
@rstockbridge will  you be submitting a PR to fix this? cc: @stkent

**Comment by rstockbridge** [comment]
I'm a Java learner - am I correct about this? Feel free to make the PR
yourself if you want, otherwise I can do it.

On May 15, 2017 9:49 PM, "morrme" <notifications@github.com> wrote:

@rstockbridge <https://github.com/rstockbridge> will you be submitting a PR
to fix this? cc: @stkent <https://github.com/stkent>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/exercism/xjava/issues/568#issuecomment-301652406>, or mute
the thread

**Comment by morrme** [comment]
@stkent  is a team member. It looks correct to me but I don't have a say.  I'd like to encourage you to try to make the change yourself, if you're up for it. I am happy to provide support, and there are several others here who are as well!

**Comment by stkent** [comment]
Disclaimer: @rstockbridge and I know each other in real life, so we've often pre-discussed issues :)

In this case, I'm not 100% sure without going and re-reading some of the details of generics what the right action would be here. There's no need to think of track maintainers as different from any other contributors when it comes to language semantics - we're all fallible and we're all still learning. If either of you are interested in doing some digging in the language documentation and settling this one either way with some references, it'd be most welcome!

**Comment by FridaTveit** [comment]
I've looked at this and I agree with @rstockbridge. I'm happy to make a PR for it unless you want to @rstockbridge? :)

**Comment by rstockbridge** [comment]
Go ahead! :)
