### ISSUE TITLE
Add .gitignore for IDE and build artifacts

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xjava#57]
I keep my working exercism directory in git, and I'm one of many... I just went to commit after working on some Java exercises and realized I ad added .gradle/ and .idea/ dirs to the working tree, among others, that shouldn't be checked into source control. It would be a good and helpful idea to add a .gitignore for typical artifacts either to each exercise directory, the java directory, or possibly a global one for exercism...

Maybe more than one of these. Might bear some discussion on the exercism/dev channel on Gitter, but I thought I'd open an issue here as well since Java's definitely a case where a lot of build/IDE artifacts are generated and I end up with quite lengthy .gitignore files in my regular projects.

**Comment by kytrinyx** [comment]
This is a really good idea. We could have a default .gitignore that gets added (if missing) to the top-level exercism dir and each of the language directories. The CLI could write it as part of configuring the client, probably.

**Comment by jtigger** [comment]
Agreed.  Personally, I create local repos for each exercise, so n>0 for the set of people who'd prefer it at the per-exercise level. :)

I can't think of a reason why we couldn't just add these to each exercise directory.

**Comment by kytrinyx** [comment]
If we have a shared language-level gitignore, or even a shared exercism-wide gitignore, the API could serve it up and the CLI could make sure to write it wherever it is missing.

**Comment by canweriotnow** [comment]
I'll add it to my TODO list, if no one else gets to it sooner. Maybe we can
collect .gitignore entries on a per-track basis, or create a global issue
under x-common or someplace and break it down by language within the issue?
I like doing common things in one place, but whatever makes the most sense
to others...

**Comment by jtigger** [comment]
yeah, yeah, yeah... no, no, no... what @kytrinyx said absolutely makes sense.  I think it would be helpful for it to be in a repo that all track maintainers have read/write on... not that these kinds of things come up very often.

BTW, @canweriotnow, I'm just delighted to see you digging in on the CLI — I find your commitment and enthusiasm inspiring!

**Comment by jtigger** [comment]
... aaaaaand we got bit by this one. :)  This gets addressed (at least for IntelliJ and Gradle) with #95.

**Comment by jtigger** [comment]
Should have been closed with #95.
