### ISSUE TITLE
Do we need to explain what a "sut" is?

### ISSUE THREAD

**Issue by stkent** [exercism/xjava#605]
In a recent pull request I noticed that some tests (e.g. `binary-search`) use the term [`sut`](https://en.wikipedia.org/wiki/System_under_test). I'm familiar with this, and it seems disciple-wide rather than Java-specific, but I didn't know if new practitioners may still potentially find it confusing. There are a few actions we could take here;

- do nothing; assume it's clear as-is, when used;
- standardize tests so that they all use `sut`, and add contextual commentary the first time it's used;
- standardize tests so that they all avoid using `sut`;
- probably others I haven't thought of.

Looking for opinions, @exercism/java! :)

**Comment by FridaTveit** [comment]
This should now be captured in issues #621, #622, #623 and #624 :)

**Comment by stkent** [comment]
Awesome, thanks!
