### ISSUE TITLE
Should we remove final from starter implementations?

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#640]
We recently removed `final` from test classes so that it wouldn't be confusing to people less familliar with Java. I think this is just as important in the starter implementations, possibly even more important because people have to actually modify the starter implementations and therefore definitely need to understand them. 

It also came up that we could remove `public` from these classes as well. I think the `public` keyword is more widely used and therefore less confusing. But less syntax is still probably better to make it easier for people to understand. And it could be worth leaving it out to show that best practice is to make classes package private where possible.

Thoughts @exercism/java?

**Comment by stkent** [comment]
I'm a +1 to this; using `final` in starter implementations potentially impacts implementation.

**Comment by stkent** [comment]
Let's capture this as a policy; @FridaTveit would you be able to add a new policy based on this decision in the POLICIES doc? Once that's done I think we can close this out :)

**Comment by FridaTveit** [comment]
Sure, will do! :)
