### ISSUE TITLE
Remove final from starter implementations

### ISSUE THREAD

**Issue by FridaTveit** [exercism/xjava#642]
We have decided to remove the `final` keyword from class declarations in starter implementations as it could be confusing to people not familiar with Java. See issue #640 and issue #571 for discussion.

The exercises with `final` in the starter implementation are:
- [ ] acronym
- [ ] all-your-base
- [ ] bracket-push
- [ ] change
- [ ] diamond
- [ ] flatten-array
- [ ] luhn
- [ ] minesweeper
- [ ] ocr-numbers
- [ ] perfect-numbers
- [ ] queen-attack (both `QueenAttackCalculator` and `BoardCoordinate`)
- [ ] rectangles
- [ ] robot-simulator (both `Robot` and `GridPosition`)
- [ ] saddle-points (both `Matrix` and `MatrixCoordinate`)
- [ ] scrabble-score
- [ ] secret-handshake
- [ ] sublist
- [ ] wordy

**Comment by vivshaw** [comment]
Should final be removed from just the starter class in `main`, or also removed from the example implementation in `example`?

**Comment by stkent** [comment]
Removing from the starter class only is perfect! Thanks for taking this on :)

The example implementations are for track maintenance purposes only, so the authors of these solutions are free to write code as they normally would :)

**Comment by stkent** [comment]
Closed by #650 💪
