### ISSUE TITLE
nucleotide-count maybe not a good second problem 

### ISSUE THREAD

**Issue by masters3d** [exercism/xjava#65]
Some languages are harder than others but I don't think introducing users to Abstract types in their second exercise is the best. 

For example, In nucleotide-count the second test requests the user to return a dictionary of some sort. 

Well, what is the actual return type of that dictionary, Map, HashMap, Dictionary? 
Example Error.

```
java.lang.AssertionError: expecting:
<{'T'=0, 'G'=0, 'A'=0, 'C'=0}>
 to contain:
<[MapEntry[key=A, value=0], MapEntry[key=C, value=0], MapEntry[key=G, value=0], MapEntry[key=T, value=0]]>
 but could not find:
<[MapEntry[key=A, value=0], MapEntry[key=C, value=0], MapEntry[key=G, value=0], MapEntry[key=T, value=0]]>
```

Granted, I've been spoiled with SwiftLang

**Comment by kytrinyx** [comment]
We could do a couple of things here... either simplify the exercise, or move it so it's not second. Thoughts, @jtigger?

**Comment by masters3d** [comment]
Noob mistake. Closing. See PR
http://stackoverflow.com/questions/439485/is-there-a-difference-between-single-and-double-quotes-in-java
