### ISSUE TITLE
How to submit Etl?

### ISSUE THREAD

**Issue by bleLLL** [exercism/xjava#71]
Hey, my etl.java is in  ~/exercism/java/etl/src/main/java directory, but when I try to submit it with full path 

    exercism submit src/main/java/etl.java

 I get an error 

    Unable to submit - unable to identify track and problem

or if I try to submit without providing a path 

    The system cannot find the file specified.

Where am I supposed to move it to? 

I tried moving it to all the directories but it's not working.

**Comment by bleLLL** [comment]
Had bad dir in config file.

**Comment by kytrinyx** [comment]
Glad you sorted it out. We're in the process of improving the error message when this happens.
