### ISSUE TITLE
Add new exercise hexadecimal

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xjava#72]
@jtigger I don't see this exercise in the 'forgone' list for this track.  I would be happy to add it and additional exercises as time allows if you think it's helpful.  Let me know.  Thanks!

**Comment by jtigger** [comment]
That would be lovely!  Yes, please!

----
(dictation taken by Thumba Leena)

**Comment by matthewmorgan** [comment]
Closed by #75
