### ISSUE TITLE
Atbash-Cipher: build.gradle is empty

### ISSUE THREAD

**Issue by blemale** [exercism/xjava#81]
The build.gradle for the atbash-cipher exercise is empty.

**Comment by sit** [comment]
Does #78 not play well with how build files are downloaded by the client @jtigger?

I had assumed that since we were injecting plugins in the top level build it would continue to work. But if each folder is sent independently, that approach won't work. :-(

**Comment by kytrinyx** [comment]
We haven't implemented a way to send common/shared code via the client.

**Comment by jtigger** [comment]
doh!  There's a gap in the CI build: that it doesn't verify that the client continues to work with it.  That will be a great add.

I forgot about this fact, @sit, when reviewing your commit to pull in duplicated dependencies.  That's actually why I didn't do it.  Sort-term fix is to revert that commit.

So far, once exercises are written, they don't get much traffic.  Changing dependency versions isn't too bad with text power tools (global search & replace).
