### ISSUE TITLE
exercism-ified java icon :)

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#84]
I've been working on making the various language icons a little bit more uniform. I don't know graphics, so I've been writing scripts to decode the PNGs and then rewrite them the way I want. It's a little bit tedious, and I haven't figured out how to smooth the edges, but I'm pretty excited about how it's turning out... and I just wanted to share. Hence the issue :)

![java](https://cloud.githubusercontent.com/assets/276834/12076329/66e3a2d4-b164-11e5-88ed-53401ae64af0.png)

**Comment by jtigger** [comment]
Nice!  They all look great together, on the site, too. :)

**Comment by kytrinyx** [comment]
I'm pretty pleased. I'm *not* going to tell you how many hours I spent on this. I will show you my fancy binary png color rewriter, though, next time we meet.
