### ISSUE TITLE
JSON error in acronym

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjava#94]
The API is blowing up when trying to serve the new acronym exercise. I'll try to take a look at it today, but if you happen to have a suspicion about what's going on then now's your chance :)

**Comment by matthewmorgan** [comment]
Ouch. That was probably something wrong in my PR. I'll look as soon as I
can.

**Comment by kytrinyx** [comment]
If not no worries, I can temporarily take out that commit from the API so that people don't automatically get that exercise. Let me know if you want me to do that.

**Comment by matthewmorgan** [comment]
It's going to be at least a couple of hours before I can look. Helping my
daughter with math homework 😊

**Comment by kytrinyx** [comment]
Yay! OK, I'll take it off for now.

**Comment by matthewmorgan** [comment]
I think I see the problem.  It looks like the exercise is not actually built...

**Comment by matthewmorgan** [comment]
@jtigger I could use your help here.  Not sure why there's no 'acronym' directory in 'xjava' root.  I'm guessing this is the problem but not sure how to solve it.

**Comment by kytrinyx** [comment]
Here's the actual error: `source sequence is illegal/malformed utf-8`

**Comment by kytrinyx** [comment]
Ooh. `.jar`. I don't think we can handle that.

**Comment by matthewmorgan** [comment]
Thanks @kytrinyx .  If you or @jtigger could check out the PR #95 and let me know if this fixes the problem...

**Comment by kytrinyx** [comment]
I think it did, it just took a while.

**Comment by jtigger** [comment]
Poopy scoop!  I missed this.

The PR included the gradle wrapper but it didn't show up in the detailed diffs.  I didn't review the file list in the PR, just the text diffs.

I've got a few minutes before bedtime, here...
